### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by otaccato** [al132mc/antimatter-chemistry#1]
If i try to start my world, the game crashes. After I tried to go to the nether.

**Comment by al132mc** [comment]
Could you please give me a crash log?

**Comment by al132mc** [comment]
Nevermind, found the mod that was causing it. Fixed in 0.4.7

**Comment by otaccato** [comment]
When will it come?

**Comment by otaccato** [comment]
Cause i have holydays and i wanna play a little bit
