### ISSUE TITLE
Chapter 2 - Pottasium Chloride

### ISSUE THREAD

**Issue by correcthorsebatterystaple** [al132mc/antimatter-chemistry#100]
The quest requires the player to collect 80 moles of KCl, however, this counter doesn't increment beyond 64 even when the player has collected beyond 64 moles. This prevents the player from completing the quest even though 80 moles have been collected.

**Comment by Next-victim** [comment]
Temporary solution is: (in SP) to close the world and reopen it or (in MP) leave the server and re-enter it.

This is still an issue that needs fixing but, because of the work around, it’s not progression breaking.
