### ISSUE TITLE
Plant Interactor

### ISSUE THREAD

**Issue by SuperFurias** [al132mc/antimatter-chemistry#103]
I don't know, the plant interactor seems to work perfectly but ..... it doesn't consume the crop ... for example I have a beetrot field, I put the plant interactor, he continues to collect the beetrot without consuming them ... in the sense that the plant remains 100% and he continues to collect seemingly indefinitely (as long as I give him energy) without the need for the plant to grow again .. is it a bug?

**Comment by al132mc** [comment]
Should be fixed in 1.2.17 by [this mod update](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/2745321)

**Comment by Firecube247** [comment]
This still seems to be an issue in the newest version of the modpack (1.4.4). Plant gatherer also doesn't work.
