### ISSUE TITLE
Draconium Ore and Exchanging Gadget

### ISSUE THREAD

**Issue by SuperFurias** [al132mc/antimatter-chemistry#105]
In the deep dark I found a Draconium Ore (strangely, there shouldn't be) So I went to see what he told me in JEI and he said "generation disabled, drop disabled" so I thought "if the gap should not drop anything" I broke it and in fact nothing has dropped me, then I thought "I recently crafted the Exchanging gadget.. maybe I can try" I found another one and guess what? gave me 2 bits of draconium dust

**Comment by al132mc** [comment]
Should be fixed in 1.2.11, draconium ore has been blacklisted from both building gadgets exchangers and the exchangers mod exchangers
