### ISSUE TITLE
Jei Integration Mod

### ISSUE THREAD

**Issue by SuperFurias** [al132mc/antimatter-chemistry#107]
Can you add the Jei Integration mod? I had to download it separately because I needed a way to see directly into the jei without crafting every single item, what was the item that had the most durability (No, F3+H does not work in the jei, only in the inventory. and the item must be damaged). I discovered that the Diamond Sugar Cane Hoe is the most durable hoe of all (I needed a hoe where I could apply an enchant, if I wanted it indestructible I used the tinker) Or I want to know how much time a particular item burns, with jei integration I can

In this case the enchant that I had to apply was Nature's Blessing III (it turns any hoe into a hoe that makes plants grow or saplings with the right button, very useful) So I didn't have to craft the bone meal every time

**Comment by al132mc** [comment]
Added in 1.2.11
