### ISSUE TITLE
No recipe for the elytra

### ISSUE THREAD

**Issue by Animaly0** [al132mc/antimatter-chemistry#108]
I'm trying to craft opinium from extra utilities taht needs elytra  but I can't see any recipe nor any end cities dimlet

**Comment by Next-victim** [comment]
Seconded for a request for a way to get an elytra. Suggest maybe using a mildly expensive ingot from alchem as a component for crafting it or as a super rare drop from shulkers.

**Comment by al132mc** [comment]
Added a recipe in 1.2.11, thank you
