### ISSUE TITLE
Add a recipe to smelt Tinkers' Armory armor into ingots.

### ISSUE THREAD

**Issue by TimelessRebornMC** [al132mc/antimatter-chemistry#109]
I made Steel Armor for the Ch3 quest but since I already had Manyullyn, I planned on using Manyullyn. I was hoping to smelt my Armor into Steel to use for machines but I can't. 
![2019-06-26_16 30 31](https://user-images.githubusercontent.com/52262808/60221769-c7886380-982f-11e9-9ff7-ce2b47efb66b.png)

**Comment by al132mc** [comment]
I probably won't add a recipe for this, but I have removed the quest that requires steel armor in 1.2.11
