### ISSUE TITLE
Can't craft Angel Ring

### ISSUE THREAD

**Issue by StewartNZ** [al132mc/antimatter-chemistry#115]
I was trying to make the angel ring it when I had everything in a crafting table the product slot was empty. I tried making any of them and none worked. I tried crafting it inside a RS crafting grid, crafting station and vanilla crafting table.

![angelring](https://user-images.githubusercontent.com/12867347/60479880-87b3f700-9cdb-11e9-94de-438eb6e432c1.PNG)

**Comment by al132mc** [comment]
Changed the recipe and fixed this in 1.2.13
