### ISSUE TITLE
[Mod Sugesstion] For Avaritia

### ISSUE THREAD

**Issue by Krixiz** [al132mc/antimatter-chemistry#116]
Please add mod that help us getting through pure anti-matter ingot

My suggestion is Fluid Cow:
Molten Antimatter (Infinity)

**Comment by MasterEnderman** [comment]
This won't happen because the avaritia stuff is designed to be the end game of the pack and we won't add any way to work around it without investing the time and resources it takes to set up the production of the Pure Antimatter Ingots.
