### ISSUE TITLE
Task Screen from FTBQuests do not behave properly, always a 1x1

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#117]
The tast screen quest gives 10 screens but players can only place them as 1x1. This is documented in Direwolf20's play as well as multiple times in the server. 

I believe this only started happening around 1.2.10.

**Comment by Attikitty13** [comment]
Same

**Comment by mtbrenner** [comment]
1.2.13 official server, tried to place 3x3 block, only 1x1 was placed. I watched Ector's YT so I know that the whole 3x3 should be placed. Also after selecting the 10b water quest, the 1x1 block looked like a tank but I could not empty the water bucket into it. Delivering the bucket inside the questbook worked, and then the tank visuals showed that 1b had been filled in.

**Comment by al132mc** [comment]
The NBT was changed for the screens, the quest in chp 1 should now award the fixed task screens with the appropriate NBT. Re-open/create a new issue if there are still issues after updating to 1.2.14
