### ISSUE TITLE
Tiny Charcoal (Tiny Progressions) can be used in the Induction Smelter for Steel.

### ISSUE THREAD

**Issue by OrangesOrigin** [al132mc/antimatter-chemistry#118]
Tiny Charcoal from Tiny progression is currently able to be used for steel smelting.
1 Charcoal is 8 Tiny charcoal which would make 2 steel ingots.
Other methods take 4 coal total to make 1.

**Comment by al132mc** [comment]
Should be fixed in 1.2.13
