### ISSUE TITLE
[1.2.12] Task Screen not accepting fluids

### ISSUE THREAD

**Issue by mtimyself** [al132mc/antimatter-chemistry#119]
I can set a task on the Task Screen but when trying to right click it with a bucket nothing happens and there is an error in the server log for each right click.

https://pastebin.com/MYWUTZLa

**Comment by al132mc** [comment]
Strange, let me know if you still experience this in 1.2.13

**Comment by tuckerliv** [comment]
chatted on discord too.  I can reproduce on a server on 1.12 and 1.13.  It works in single player mode for me.  I did find as a work around on the server you can go into the quest book, click the Lots o' Wadder quest, and click the water under tasks to submit as a work around.  I did try fluidducts as a test and the do not attach to the screen.

**Comment by al132mc** [comment]
Hopefully should be fixed in 1.2.14 - As long as you either craft a new screen or use the new ones awarded in chp 1. Please re-open/create a new issue if there are still problems
