### ISSUE TITLE
End Game Generators

### ISSUE THREAD

**Issue by pip69** [al132mc/antimatter-chemistry#12]
Make the nether star & rainbow generators as end game items requiring Avartia.
 
Need to verify that there are ways to fuel every generator.  (I'll come back for this if no one comments.)
Pink generator probably needs to be able to use some "pink" elements as fuel

**Comment by pip69** [comment]
For the Slime Generator, allow condensed milk to replace milk.

For the Pink Generator, while there are a lot that could be consider "pink" , maybe just allow Magnesium Oxide & Methane.  Both relatively easy to get.

**Comment by al132mc** [comment]
I've implemented all of these in v0.4.20 except for condensed milk. Hopefully i'll get that figured out soon
