### ISSUE TITLE
Concrete instead of Antimatter

### ISSUE THREAD

**Issue by Amaery** [al132mc/antimatter-chemistry#122]
So umm the floor should be Antimatter, so quests can be completed. But my floor is all just concrete. i tried reinstalling the modpack and still running into the same issue.

I made some random screenies idk what could help with debugging this, if it is even a bug and not just something dumb im doing.
Oh yea, not sure if it should show a recipe or not, but its not showing it 🤔
![Annotation 2019-07-03 220328](https://user-images.githubusercontent.com/51875647/60625123-cda5b380-9dde-11e9-8869-f94ef5f8df57.png)
![Annotation 2019-07-03 220409](https://user-images.githubusercontent.com/51875647/60625124-cda5b380-9dde-11e9-9607-2a0a75114b5d.png)
![Annotation 2019-07-03 220506](https://user-images.githubusercontent.com/51875647/60625126-cda5b380-9dde-11e9-9806-0105ad4c06bb.png)

**Comment by al132mc** [comment]
I would suggest re-installing the pack. Make sure you have the /scripts/ folder

**Comment by Amaery** [comment]
i have reinstalled the pack twice sofar, and the scripts folder is there, but still no luck.

Also not sure if its related or not, but like when i launch the game, there is like a pop-up which im guessing normally would introduce the pack, but the one i see just has like an example of what the pop-up can do.
![Annotation 2019-07-03 223720](https://user-images.githubusercontent.com/51875647/60626578-21b29700-9de3-11e9-86a9-ec44f14a9c6c.png)

**Comment by MasterEnderman** [comment]
are you using the newest version of the pack? because this pop-up was removed several versions ago

**Comment by al132mc** [comment]
My guess is neither the config nor script folders are being loaded. How are you running the pack? With a luancher? (like twitch or multiMC?)

**Comment by Amaery** [comment]
yes, running through twitch, and no pop-ups to update appear on twitch so im guessing its the most recent version

**Comment by al132mc** [comment]
Could you please double-check which version you're running? It should say so in your list of modpacks 
![image](https://user-images.githubusercontent.com/39097092/60628129-c3bb8a80-9db5-11e9-8b9e-167f3cd4e874.png)

**Comment by Amaery** [comment]
Looks like its the newest version afterall.
![Annotation 2019-07-03 231503](https://user-images.githubusercontent.com/51875647/60628230-6987ed00-9de8-11e9-8224-af1778e60457.png)

**Comment by Next-victim** [comment]
Anaery, the pack was updated yesterday. The image you sent says the pack was updated in February. Please update the pack

**Comment by Amaery** [comment]
odd that, twitch is showing no update and the date is 02/07/2019 dd/MM/yyyy

**Comment by Next-victim** [comment]
My bad, read the date the other way around.

Have you tried the “repair pack” option?

**Comment by Amaery** [comment]
yea i tried reinstalling, repairing, a few times and that sadly did nothing

**Comment by Amaery** [comment]
So i figured out the issue. Its a very specific thing. Buuuuuut....
basically installing twitch anywhere but the default location (Fodlers contained in the User directory should be fine) causes minecraft not to load the scripts, uhmmm... yea so thats that, heh
