### ISSUE TITLE
Basic Draconic Infusion requests 8 basic injectors, but you need 9

### ISSUE THREAD

**Issue by daddy77gaming** [al132mc/antimatter-chemistry#125]
To do the next level of fusion injectors you need 9 basic injectors, bc you need 8 and another basic injector to create the first Wyvern infusion injector, Might as well ask for 9 in the basic injector quest ;)

**Comment by daddy77gaming** [comment]
![2019-07-04_21 16 34](https://user-images.githubusercontent.com/31905330/60686503-74568680-9ea9-11e9-97b4-851d9d91b6d9.png)

**Comment by al132mc** [comment]
Changed in 1.2.17
