### ISSUE TITLE
Draco Arcane Scepter can Player Kill in non-PVP servers

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#128]
The Draco Arcane Scepter causes an orb to fly out and cause a lightning strike when it touches an entity. This can be used to kill a player via fire and lightning. This overpowers even regen 3 and saturation 3 (see screenshot with environmental controller active).

Screenshot of player Kemsku being killed (with permission) on 1.2.12 via lightning and fire damage in the Anti-matter Overworld

![2019-07-05_18 02 36_2](https://user-images.githubusercontent.com/51034324/60746906-bcc87f80-9f4f-11e9-8b7d-ad7e5136512d.png)

**Comment by al132mc** [comment]
I think i'll just leave this up to server admins to police. A+ for the demonstration though
