### ISSUE TITLE
Big Pouch deleting contents warning

### ISSUE THREAD

**Issue by SummitSummit** [al132mc/antimatter-chemistry#130]
Probably not a bug that can be easily fixed so I'll just post a warning for others. 
When you update from 1.2.12 to 1.2.13 if you are using the "Big Pouch" from Tiny Progressions it will delete the contents when you update.  
Easy fix, empty your Big Pouch before updating. 

Edit:
Hmm...  There was no update to the pack, but when I fired up the pack today, my Big Pouch was empty again.  I think I'll just trash it.  Kind of a bummer though. 

Edit2:
Reported on Tiny Progressions Github.

**Comment by al132mc** [comment]
I have decided to disable the recipe for the pouches, starting in 1.2.14
