### ISSUE TITLE
ingotCobalt from TConstruct not compatible in Chemical Combiner

### ISSUE THREAD

**Issue by dingsbums** [al132mc/antimatter-chemistry#131]
Have a ingotCobalt from tconstruct:ingot and it doesn't work in Combiner recipe for the blank data model. I have to dissolve and combine again to make it work.

**Comment by Next-victim** [comment]
There is the forge lexicon, which can convert between ingots. Not a fix but might help temporarily.

**Comment by al132mc** [comment]
Should be fixed in 1.2.14 - All methods that previously gave tinkers cobalt ingots should now give alchemistry cobalt ingots
