### ISSUE TITLE
Question: Reliable Energy Production

### ISSUE THREAD

**Issue by IulianDan** [al132mc/antimatter-chemistry#132]
Can somebody please tell me what is the best way to get a lot of RF/FE Mid Game?

**Comment by taint19711** [comment]
Well depending on what chapter you are in you could make a fission reactor

**Comment by taint19711** [comment]
If you have questions I will be in voice chat here in about 5 min

**Comment by IulianDan** [comment]
I planned on getting the Fission Reactor but was hoping there would be a better option.
Thx anyway.
