### ISSUE TITLE
Error when loading pack

### ISSUE THREAD

**Issue by samuelcoelho729** [al132mc/antimatter-chemistry#134]
Hi! This is most likely an issue on my side, but I get this error when I attempt to load the pack from the Twitch launcher.

`Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by al132mc** [comment]
Are you able to launch any other modpacks? In any case, make sure that you are using Java 8

**Comment by al132mc** [comment]
To anyone who comes across this issue: Please ensure you are using Java 8, closing
