### ISSUE TITLE
Stuck in chapter 3

### ISSUE THREAD

**Issue by nightmorphis** [al132mc/antimatter-chemistry#135]
I'm not able to activate the quest about the "Induction Smelter", even if I completed all the ones before that one, so I can't continue along the quest book.
I already tried to validate files, exit/enter, create a new game, craft or even give me a bunch of smelters.

![stuck](https://user-images.githubusercontent.com/52762472/61006035-ae240300-a369-11e9-820c-3e1ca35eb453.jpg)

**Comment by al132mc** [comment]
Hm, it looks like it also wants you to do the pink dye quest too, based on the directions of the arrows. Admittedly that's a bit confusing and something I should tweak. I'll leave this issue open so I remember to change it.

**Comment by nightmorphis** [comment]
oh, that's why! thank you!

**Comment by Next-victim** [comment]
Request to either put the pink dye in the quest line directly via jaggedly moving the lines around or to remove the pink dye quest. 

This has happened a few times on the discord server.

**Comment by al132mc** [comment]
I decided to just remove the pink dye quest in 1.2.14
