### ISSUE TITLE
Shift Click bucket of XP into black hole tank caused ticking tile

### ISSUE THREAD

**Issue by Osgz11** [al132mc/antimatter-chemistry#137]
Shift clicked a bucket of XP into a Black Hole Tank and caused a unrecoverable crash Ticking Tile. I have tried to load the mod 3 times this is the latest crash report.

[crash-2019-07-12_21.06.06-server.txt](https://github.com/al132mc/antimatter-chemistry/files/3388444/crash-2019-07-12_21.06.06-server.txt)

**Comment by al132mc** [comment]
I don't have any easy solutions for you unfortunately if you don't have a recent backup. However, if you want to save your world you can remove Industrial Foregoing, then start the pack back up. Then close it again and add the mod pack. This will delete all blocks/items from Industrial Foregoing which is bad, but it's better than losing your world entirely...

**Comment by al132mc** [comment]
https://github.com/Buuz135/Industrial-Foregoing/issues/586

**Comment by uberfuzzy** [comment]
in the forge config, there is an option to remove the TE causing the problem, rather than crash.
Change to true, Start world, Save, Exit, Change config back to false, Continue playing as normal.
The most you might lose is the blackhole tank, or possibly the bucket.

**Comment by al132mc** [comment]
Yeah, I actually realized that since I commented a week ago, I just forgot to follow up here again. That's a good suggestion though

**Comment by Osgz11** [comment]
Thank you worked like a champ :)
