### ISSUE TITLE
Dynamo Fuels

### ISSUE THREAD

**Issue by pip69** [al132mc/antimatter-chemistry#14]
Add liquid oxygen & hydrogen for the Thermal reactant dynamo to produce RF. 
  - Are there others that would be worth while to include with this? 
  - Could this be added into Alchemistry itself instead of the pack?

**Comment by pip69** [comment]
As a follow up, consider 100 mb of liquid oxygen (that's about 11 items) and 1 item of hydrogen to produce 100,000 to 150,000 RF.
They are common items so the RF output should be at the low end.
If you can set the reaction to count for the Augment: Elemental Catalyzer, then use 100k RF as the base value.

On semi-related note, could liquid nitrogen be considered a coolant like thermal cryotheum is?

**Comment by al132mc** [comment]
I added liquid nitrogen as a Thermal Mediator coolant, and added a recipe like you suggested with liquid oxygen and hydrogen,m though I was unable to get it to work with the elemental catalyzer.. 

For now, I'm choosing quite a low generation value for the reactant dynamo, 15k RF per 100mb oxygen + 1 hydrogen. This still works out to almost 1k energy per item (for essentially worthless items you have in bullk), even if you consider the energy required to power the liquifier (5k rf per 144 mb oxygen)
