### ISSUE TITLE
[Suggestion] Things to add to Chisel and Bits

### ISSUE THREAD

**Issue by MiniKatalyst** [al132mc/antimatter-chemistry#143]
Hi there, 

If it's possible, I would love it if the Atum 2 collection of stained crystal glasses could be added to the Chisel and Bits white-list.

Pretty please and many thanks in advance.

**Comment by al132mc** [comment]
It doesn't look like Chisels & Bits has any whitelist that I can add blocks to as far as I can tell. It seems that it detects most blocks and I can those detected blocks in the config, but that seems to be it.
