### ISSUE TITLE
[Suggestion] Add cocoa bean chemical dissolver recipe

### ISSUE THREAD

**Issue by nanonator102** [al132mc/antimatter-chemistry#145]
Suggested dissolver products for cocoa beans:
Type: Relative
Rolls: 1
50% Caffeine
10% Cellulose

**Comment by al132mc** [comment]
Added in Alchemistry 1.0.28, which should be included the next time there is a pack update

**Comment by al132mc** [comment]
Added in pack update 1.2.1.5, though I used a more generous output than this
