### ISSUE TITLE
Quest for Dark Rune and Runic Tenebris Core

### ISSUE THREAD

**Issue by mtbrenner** [al132mc/antimatter-chemistry#146]

**Comment by mtbrenner** [comment]
Description says to use a dark Nether Star on a Runic Tenebris Core, but actually you have to use it on a Runic Tenebris FRAME to get the Core and then use a Rune on the Core.

**Comment by al132mc** [comment]
Is this meant for Volcano Block?

**Comment by mtbrenner** [comment]
Sorry, yes.
