### ISSUE TITLE
Add to dissolver

### ISSUE THREAD

**Issue by pip69** [al132mc/antimatter-chemistry#15]
- add Atum Sarcophagus to the dissolver.   
      You won't get many of them so 20 rolls of:
 60% beryl(4), 60% chromium (4), 60% vanadium (2), , 60% silver(8), 60% gold(8), 60% platinum(8), 60% potassium permanganate(4), 60% Iron Oxide (5), 60% strontium Carbonate (5)

**Comment by al132mc** [comment]
Added to v0.4.17, thank you for the suggestion
