### ISSUE TITLE
Uggestion: Plastic from PVC or Bakelite

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#154]
We have industrial forgoing rubbernin the pack and we have PVC as a compound. Could we have some way to transition between them? Maybe 8 PVC to a plastic with a 25% 8-roll for dissolving back?

As an alternative idea: Bakelite, which is effectively phenol and formaldehyde, is an early form of thermo-cast plastic. Maybe something from that if a more expensive recipe is needed?

**Comment by al132mc** [comment]
Added in 1.2.17
