### ISSUE TITLE
Deep Mob Lesrnin

### ISSUE THREAD

**Issue by BobAnubis** [al132mc/antimatter-chemistry#157]
Can not make the deep mob learning simulation chamber and loot fabricator?

**Comment by al132mc** [comment]
Please elaborate?

**Comment by BobAnubis** [comment]
I am not able to craft Deep Mob Learning’s Simulation Chamber and Loot Fabricator

**Comment by al132mc** [comment]
You won't be able to craft them until you get far enough in (chapter 4?) where the quests for those machines are

**Comment by BobAnubis** [comment]
I have already passed chapter four, and the recipe is still not showing up.

**Comment by al132mc** [comment]
Sorry for the late response, could you please show me a screenshot of your chapter 4 quests?

**Comment by BobAnubis** [comment]
![GITHUBPICTURE](https://user-images.githubusercontent.com/32489992/62020616-52d77a80-b189-11e9-8cf7-62e464de0aab.PNG)
 Here's the screenshot. Let me know if you can see it or not.

**Comment by FireJadian** [comment]
Out of curiosity, how did you complete these quests if you can't craft the related items?  May be related to why the recipes aren't available.

**Comment by BobAnubis** [comment]
I completed chapter 4 a few months ago.

**Comment by al132mc** [comment]
Sorry for the late response. This could possibly? be related to your world being so old. The command 
```/gamestage add @p mummy``` will fix this

**Comment by BobAnubis** [comment]
It worked, and thank you for the help
