### ISSUE TITLE
Wither and Dragon still make death sounds server wide.

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#158]
The wither and the dragon's kill cries can be heard by every player in a server.

**Comment by Next-victim** [comment]
I think I found a small bit that can fix it in the thread below.
https://bukkit.org/threads/prevent-enderdragon-sound-from-being-played-on-all-worlds.162218/

**Comment by al132mc** [comment]
I found [this mod[(https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded) a few days ago and planned on adding it in the next release

**Comment by al132mc** [comment]
Added aforementioned mod in 1.2.18
