### ISSUE TITLE
Hang glider starts ringing after changing dimensions

### ISSUE THREAD

**Issue by Dr-Game** [al132mc/antimatter-chemistry#162]
After changing dimensions, there is a chance that deploying the hang glider while in the air will produce a high-pitched, constant, monotone ringing. When shifting with the hang glider deployed in the air (a mechanic that lets you fly and descend faster), the ringing's pitch progressively gets higher as you go faster, and lower as you slow down. It will stop when you land, put up the hang glider, or switch to a different item in your hotbar. Switching dimensions again has a chance to fix it, though it may happen again if you keep switching dimensions. As far as I've tested in standard survival mode, this has happened to me in the nether, the overworld, the atum dimension, and the deep dark, though that's not to say this won't happen in other dimensions once I reach them.

**Comment by FireJadian** [comment]
I've had this issue as well, but it's a "feature" of the Hang Glider and even after toggling it off, it sometimes seems to reactivate.

I think the default hotkey for turning it off is the V key?  You can find it in Controls listed as "Vario on/off".

**Comment by Dr-Game** [comment]
You know, that actually explains a lot! My V key is bound to the Satchel's auto-pickup, which I always turn on when I go to the aforementioned dimensions for resources, and I sometimes forget to turn it off when I return to my base. I guess I just never linked the two. I'll do a bit more testing now that I know this.

**Comment by Dr-Game** [comment]
Yeah, changing the keybind for this Vario toggle seems to work for now. Sorry for the false alarm, I just didn't know this was a feature. If no one else has any related issues for this, I'll close it tomorrow.
