### ISSUE TITLE
Dysprosium work around?

### ISSUE THREAD

**Issue by dabigmoose** [al132mc/antimatter-chemistry#163]
Hey Al,

Just an FYI.  I don't know if it was intended but I was able to make Dysprosium via Fusion Crafting prior to completing the netherstar quest.

Once you get into Deep Mob Learning it is fairly easy to get the skull to make the wither skeleton data model and hence make enough skulls to kill withers to get Wither data model and netherstars.

If you want people to do hard way maybe just hide fusion controller behind the netherstar quest.  While it doesn't take nearly as long, making fusion multiblock still requires a ton of tungsten etc.

Just wanted to bring it to your attention.

-Witsend

**Comment by al132mc** [comment]
The fusion controller is now locked behind the netherstar quest in 1.2.19, thank you
