### ISSUE TITLE
Enable RTG but have them produce small power

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#175]
Could we get RTG back but have them produce microscopic power? 

Maybe 50rf/t for the max one, enough to keep a matter receiver going with rare use but not enough to use as power.

This would bring it into line with how actual RTG power works, usually they make power on the order of <1 watt. The are often used in isolated situations like deep space exploration to build charge slowly.

**Comment by al132mc** [comment]
Re-added in 1.2.20
