### ISSUE TITLE
XP duplication with Forbidden & Arcanus

### ISSUE THREAD

**Issue by Exanc** [al132mc/antimatter-chemistry#179]
Mining ores such as Runestone and Arcanus crystal ore with silk touch will drop XP.
Then placing the same ore and breaking it again will drop XP again, this can be repeated indefinitely.
In my case, I was using a TConstruct pickaxe, but the same result can be obtained with a vanilla tool.

**Comment by al132mc** [comment]
https://github.com/al132mc/antimatter-chemistry/issues/179
