### ISSUE TITLE
v0.4.19 - Issue with rendering some pattern

### ISSUE THREAD

**Issue by lagonnebula** [al132mc/antimatter-chemistry#18]
Hello, i have some issue  with some of my pattern in the refined storage crafter manager, and the same when i have them in my inventory:

I enabled CCL rtecovery attempt to see what was going.
And here the message  i got from it:
[client_error.txt](https://github.com/al132mc/antimatter-chemistry/files/3123773/client_error.txt)

I have 10 of them causing this error, with only the NBT tags changed. 
I can created pattern for other item. But not a new one for which is causing the issue ( even after destroyed them)

**Comment by al132mc** [comment]
Related to this issue, I will update the pack soon to fix this.

https://github.com/al132mc/alchemistry/issues/39

**Comment by al132mc** [comment]
Fixed in 0.4.20, thank you
