### ISSUE TITLE
NuclearCraft Basic Plating recipe doesn't work

### ISSUE THREAD

**Issue by MickGeraerds** [al132mc/antimatter-chemistry#187]
Playing on a multiplayer server, version 1.2.21. 

Im stuch in chapter 5 because the NuclearCraft Basic Plating recipe doesn't work.

Recipe in JEI says:
lead ingot/grapite dust
graphite dust/cadmium ingot

saw the recipe was suppoe to be tweaked in 1.2.20, maybe the server files didnt have the recipe updated?

**Comment by al132mc** [comment]
That is the tweaked recipe. It uses 1 cadmium ingot & 1 lead ingot instead of 2 lead ingots

**Comment by al132mc** [comment]
Please better explain your issue. What doesn't work exactly? What happens when you try to craft? Does it fail to craft? Perhaps could you include screenshots?

**Comment by MickGeraerds** [comment]
the server files are using the old recipe, after you're reply i tried using 2x lead ore instead of 1 cadmium, i got the basic plating that way. Seems the new tweaked recipe isnt included/updated in the server files

**Comment by MickGeraerds** [comment]
https://i.gyazo.com/ec3abadb658f48ce77eba162d6b8776a.png  new recipe doesn't work
https://gyazo.com/baa6267917a79e66aed0bdbb293cc2fa Old recipe shows a stack of diamonds but gives u the plating when you take them out

**Comment by al132mc** [comment]
Are you playing on the official server? On your own server? on somebody else's? It could be an error on the side of the server owner not updating the scripts. I opened up the server  zip that was uploaded and it seems to include the appropriate recipe. 

![image](https://user-images.githubusercontent.com/39097092/64197928-dbae9980-ce4c-11e9-889e-91c423ee5010.png)

**Comment by MickGeraerds** [comment]
A sub server, ill contact the server owner

**Comment by MickGeraerds** [comment]
Contacted the server admin. It seems to be an issue in his end. Thanks for the help
