### ISSUE TITLE
That is the tweaked recipe. It uses 1 cadmium ingot & 1 lead ingot instead of 2 lead ingots

### ISSUE THREAD

**Issue by MickGeraerds** [al132mc/antimatter-chemistry#188]
That is the tweaked recipe. It uses 1 cadmium ingot & 1 lead ingot instead of 2 lead ingots

_Originally posted by @al132mc in https://github.com/al132mc/antimatter-chemistry/issues/187#issuecomment-527566479_

With all due respect, could you READ the issue? As it clearly states the recipe DOES NOT WORK in MULTIPLAYER. I tried it in single player and it DOES work in SINGLEPLAYER. 

Its a very weird way to close and disregard an issue.

**Comment by al132mc** [comment]
Re-opening that issue, c.losing this one.
