### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Middelin** [al132mc/antimatter-chemistry#19]
My game crashed this morning while creating Refined Storage Patterns. The save was corrupted so I loaded a backup, but the same thing happened again when I created a pattern for a Reinforced Upgrade Kit.
Excuse the fact that I'm playing on my dumpster fire of a laptop

[crash-2019-04-27_12.38.49-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3124110/crash-2019-04-27_12.38.49-client.txt)

**Comment by al132mc** [comment]
This should be fixed in v0.4.20, your world shouldn't be corrupted once you update
