### ISSUE TITLE
Game Slowing Down Immensely When Entering/Leaving Nether

### ISSUE THREAD

**Issue by Lord-Unchemael** [al132mc/antimatter-chemistry#192]
Basically I just got to the stage where I can enter the nether, and each time I do so it just makes the game eat up all of my cpu and I don't know what to do. It makes the game unplayable and slow, and sometimes it just flat out crashes.

**Comment by al132mc** [comment]
Hm.. that's odd. I haven't heard of that happening before. I guess i'd try reducing your graphics settings if you have a low spec computer. Could you give me any other information otherwise?

**Comment by Lord-Unchemael** [comment]
I have a very high end computer.
GPU: NVIDIA Geforce RTX 2080.
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

Let me know if you need anything else.

**Comment by Lord-Unchemael** [comment]
Ok so I fixed it, I just had my render distance too high and I also turned down my particles to decreased. I guess even the most beefy of computers can be taken down by the power of modded minecraft.
