### ISSUE TITLE
more recipes unlocked bag

### ISSUE THREAD

**Issue by DenisBabutski** [al132mc/antimatter-chemistry#193]
No new recipes in the new era

**Comment by al132mc** [comment]
Could you please better explain what your problem is, perhaps with screenshots?

**Comment by DenisBabutski** [comment]
![5fSMof4Pj1w](https://user-images.githubusercontent.com/55058836/64491471-7ce48800-d271-11e9-884a-138b779eb2c9.jpg)
![Uploading S1i5yhoJVPI.jpg…]()
reset all

**Comment by DenisBabutski** [comment]
![S1i5yhoJVPI](https://user-images.githubusercontent.com/55058836/64491487-ae5d5380-d271-11e9-883a-907090391e08.jpg)
