### ISSUE TITLE
Game crushed after 2 minutes

### ISSUE THREAD

**Issue by Lietarius** [al132mc/antimatter-chemistry#195]
Game crashed in random opened windows (chest, chemical combiner, tool forge). 

Mod pack version 1.2.23, installed from Twitch launcher.

Crash log attached. 

[crash-2019-09-26_09.26.32-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3656244/crash-2019-09-26_09.26.32-client.txt)

**Comment by al132mc** [comment]
Sorry for the late response. Sometimes this bug appears with the crafting station from tinkers, at worst use the vanilla crafting table if it keeps happening.

**Comment by Melodeiro** [comment]
Or you can disable tinkers table rendering by default. I remember that problem with mekanism, but seems like that is happening with extra utilities as well
