### ISSUE TITLE
Chemical Dissolver gives out random outputs when pressing shift

### ISSUE THREAD

**Issue by Apotrox** [al132mc/antimatter-chemistry#197]
When you shift-click items into the chemical dissolver, most of the outputs are voided. But sometimes there is some random output like Aluminium Oxide when packing in Gravel or stuff.

**Comment by al132mc** [comment]
Yes, some blocks have a random chance of outputting aluminum oxide as indicated by JEI. Could you please be more specific on how exactly I can replicate the 'problem'?

**Comment by Apotrox** [comment]
And i'm a total idiot, clicked on the wrong block to look into the drop rate. Sorry for wasting your time -.-
