### ISSUE TITLE
Overworld Dimentional Cake not working

### ISSUE THREAD

**Issue by Spanky1044sback** [al132mc/antimatter-chemistry#198]
Just finished the Ender Cake quest line and went to the end. I laid down the quest rewarded Overworld Cake to head to the Overworld and nothing happened. I've tried fueling it, remaking it, cheating it in and nothing works. Is this intended or a bug?

**Comment by al132mc** [comment]
The startin dimension is the "overworld". It's purpose is to return from the end.
