### ISSUE TITLE
Crash going into Nether

### ISSUE THREAD

**Issue by magicdiablo** [al132mc/antimatter-chemistry#2]
Crashing old world going into the nether.  Crash report below.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Alchemistry Plugin (alchemistry-0.9.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.1+build41-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.9.1.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/13/19 5:22 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76663_a(ExtendedBlockStorage.java:575)
	at net.minecraft.network.play.server.SPacketChunkData.func_189556_a(SourceFile:145)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:39)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76663_a(ExtendedBlockStorage.java:575)
	at net.minecraft.network.play.server.SPacketChunkData.func_189556_a(SourceFile:145)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:39)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: New Version
	All players: 1 total; [EntityPlayerMP['magicdiablo'/73, l='New Version', x=-472.23, y=109.00, z=-187.53]]
	Chunk stats: ServerChunkCache: 348 Drop: 0
	Level seed: -6907300119804897541
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360869952 bytes (344 MB) / 1534590976 bytes (1463 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 4 total; -Xmx7168m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                             | Signature                                |
	|:------ |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2823             | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | openmodscore        | 0.12.1                   | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore         | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA | forgelin            | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHIJA | alib                | 1.0.8                    | alib-1.0.8.jar                                     | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia            | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
	| LCHIJA | placebo             | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJA | singularities       | 2.3.2                    | Singularities-1.12.2-2.3.2.jar                     | None                                     |
	| LCHIJA | crafttweaker        | 4.1.17                   | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
	| LCHIJA | alchemistry         | 0.9.2                    | alchemistry-0.9.2.jar                              | None                                     |
	| LCHIJA | apotheosis          | 1.9.1                    | Apotheosis-1.12.2-1.9.1.jar                        | None                                     |
	| LCHIJA | applecore           | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | mtlib               | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
	| LCHIJA | modtweaker          | 4.0.17                   | modtweaker-4.0.17.jar                              | None                                     |
	| LCHIJA | jei                 | 4.15.0.275               | jei_1.12.2-4.15.0.275.jar                          | None                                     |
	| LCHIJA | appleskin           | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCHIJA | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | atum                | 2.0.3                    | Atum-1.12.2-2.0.3.jar                              | None                                     |
	| LCHIJA | betterbuilderswands | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar  | None                                     |
	| LCHIJA | blockcraftery       | 1.12.2-1.2.0             | blockcraftery-1.12.2-1.2.0.jar                     | None                                     |
	| LCHIJA | bookshelf           | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | redstoneflux        | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore        | 2.4.10                   | BrandonsCore-1.12.2-2.4.10.198-universal.jar       | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | chesttransporter    | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
	| LCHIJA | chiselsandbits      | 14.31                    | chiselsandbits-14.31.jar                           | None                                     |
	| LCHIJA | cofhcore            | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
	| LCHIJA | cofhworld           | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | mantle              | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                           | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                   | None                                     |
	| LCHIJA | conarm              | 1.2.3.1                  | conarm-1.12.2-1.2.3.1.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | controlling         | 3.0.6                    | Controlling-3.0.6.jar                              | None                                     |
	| LCHIJA | craftingtweaks      | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
	| LCHIJA | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
	| LCHIJA | crafttweakerjei     | 2.0.3                    | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
	| LCHIJA | cropdusting         | 0.7                      | CropDusting-0.7-[1.12.2].jar                       | None                                     |
	| LCHIJA | darkutils           | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | patchouli           | 1.0-18                   | Patchouli-1.0-18.jar                               | None                                     |
	| LCHIJA | thermalfoundation   | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | deepmoblearning     | 1.12.2-2.5.0             | deepmoblearning-1.12.2-2.5.0-universal.jar         | None                                     |
	| LCHIJA | diethopper          | 1.1                      | diethopper-1.1.jar                                 | None                                     |
	| LCHIJA | theoneprobe         | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LCHIJA | dimensionaledibles  | 1.3.1                    | DimensionalEdibles-1.12.2-1.3.1.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | discordcraft        | 1.0                      | DiscordCraft-1.0.2.jar                             | None                                     |
	| LCHIJA | draconicevolution   | 2.3.21                   | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |
	| LCHIJA | enderstorage        | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | fastleafdecay       | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | foamfix             | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
	| LCHIJA | ftblib              | 5.4.1.95                 | FTBLib-5.4.1.95.jar                                | None                                     |
	| LCHIJA | ftbutilities        | 5.4.0.92                 | FTBUtilities-5.4.0.92.jar                          | None                                     |
	| LCHIJA | itemfilters         | 1.0.3.11                 | ItemFilters-1.0.3.11.jar                           | None                                     |
	| LCHIJA | ftbquests           | 1.5.1.144                | FTBQuests-1.5.1.144.jar                            | None                                     |
	| LCHIJA | ftbbackups          | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.3.jar                    | None                                     |
	| LCHIJA | gamestages          | 2.0.114                  | GameStages-1.12.2-2.0.114.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | gravestone          | 1.10.2                   | gravestone-1.10.2.jar                              | None                                     |
	| LCHIJA | reborncore          | 3.13.12.447              | RebornCore-1.12.2-3.13.12.447-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | hardcoremapreset    | 4.2.3.39                 | HardCoreMapReset-4.2.3.39.jar                      | None                                     |
	| LCHIJA | harvest             | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                          | None                                     |
	| LCHIJA | incontrol           | 3.9.6                    | incontrol-1.12-3.9.6.jar                           | None                                     |
	| LCHIJA | inventorytweaks     | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LCHIJA | jeresources         | 0.9.0.53                 | JustEnoughResources-1.12.2-0.9.0.53.jar            | None                                     |
	| LCHIJA | mcjtylib_ng         | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                            | None                                     |
	| LCHIJA | moreoverlays        | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                     | None                                     |
	| LCHIJA | mousetweaks         | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| LCHIJA | mputils             | 1.5.6                    | MPUtils-1.12.2-1.5.7.jar                           | None                                     |
	| LCHIJA | mpbasic             | 1.4.7                    | mpbasic-1.12.2-1.4.11.jar                          | None                                     |
	| LCHIJA | neat                | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| LCHIJA | nuclearcraft        | 2.15                     | NuclearCraft-2.15-1.12.2.jar                       | None                                     |
	| LCHIJA | openmods            | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks          | 1.8                      | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | oreexcavation       | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
	| LCHIJA | recipestages        | 1.1.1                    | RecipeStages-1.1.1.jar                             | None                                     |
	| LCHIJA | refinedstorage      | 1.6.14                   | refinedstorage-1.6.14.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | refined_avaritia    | 2.6                      | refined_avaritia-1.12.2-2.6.jar                    | None                                     |
	| LCHIJA | rftools             | 7.61                     | rftools-1.12-7.61.jar                              | None                                     |
	| LCHIJA | rftoolsdim          | 5.64                     | rftoolsdim-1.12-5.64.jar                           | None                                     |
	| LCHIJA | thermalexpansion    | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics     | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | simplyjetpacks      | 2.2.11.64                | SimplyJetpacks2-1.12.2-2.2.11.64.jar               | None                                     |
	| LCHIJA | solcarrot           | 1.12.2-1.6.3             | solcarrot-1.12.2-1.6.3.jar                         | None                                     |
	| LCHIJA | storagedrawers      | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | tp                  | 3.2.32                   | tinyprogressions-1.12.2-3.3.32-Release.jar         | None                                     |
	| LCHIJA | toastcontrol        | 1.8.0                    | Toast Control-1.12.2-1.8.0.jar                     | None                                     |
	| LCHIJA | wanionlib           | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
	| LCHIJA | waterfreefarming    | 2.0.5                    | waterfreefarming-2.0.5.jar                         | None                                     |
	| LCHIJA | xnet                | 1.7.6                    | xnet-1.12-1.7.6.jar                                | None                                     |
	| LCHIJA | phosphor-lighting   | 1.12.2-0.2.1             | phosphor-1.12.2-0.2.1+build41-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | mysticallib         | 1.12.2-1.1.1             | mysticallib-1.12.2-1.1.1.jar                       | None                                     |
	| LCHIJA | unidict             | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
Alchemistry Plugin (alchemistry-0.9.2.jar)
  al132.alchemistry.core.AlchemistryTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.1+build41-universal.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ApotheosisCore (Apotheosis-1.12.2-1.9.1.jar)
  shadows.ApotheosisTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.12.447
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['magicdiablo'/73, l='New Version', x=-472.23, y=109.00, z=-187.53]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by al132mc** [comment]
Phosphor was the culprit, fixed in v0.4.7
