### ISSUE TITLE
Server starts in standard overworld

### ISSUE THREAD

**Issue by RobertLSnead** [al132mc/antimatter-chemistry#202]
What should the level-type = in the server properties to generate the standard template?
Default is obviously not the right option.  Please help!

**Comment by ghost** [comment]
It doesn't use a level type, it uses a pre-generated world which is distributed with the server files (A folder entitled "world", which will work automatically with the server.properties file distributed with the server download)

**Comment by ghost** [comment]
If you are still having issues please re-open this issue or create a new issue
