### ISSUE TITLE
Milk Texture

### ISSUE THREAD

**Issue by Ethan-Dankiw** [al132mc/antimatter-chemistry#203]
When putting Tinkers Construct milk in an Ex Nihilo barrel (Stone or wood) the game just instantly crashes, while making it impossible to join the world without removing the barrel filled with milk.

[crash-2019-10-20_15.10.45-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3747485/crash-2019-10-20_15.10.45-client.txt)

**Comment by OniyaMCD** [comment]
Ex Nihilo isn't in this pack?
