### ISSUE TITLE
Task Screen doesn' accept fluids from bucket

### ISSUE THREAD

**Issue by cyacedev** [al132mc/antimatter-chemistry#207]
I'm having a problem when trying to complete the Quest "Lots o' Wadder". I cannot use a bucket of water on the task screen. Weirdly enough, **it works in singleplayer but not multiplayer**. 

If I right-click the Task Screen with a Bucket of Water nothing happens and following error occurs on the server log:
https://pastebin.com/QvBG0HYZ

This issue is probably related to #119 but was probably fixed in 1.2.14 (I'm using 1.2.25 on both client and server). I did use a new task screen (also cheated one in), still the same issue.

**Comment by Cyprex** [comment]
Do you have access to the quest? It lets you select quests you haven't unlocked yet, but submission fails.

**Comment by cyacedev** [comment]
Yes, i do have access as i can manually submit the buckets (which is how i solved my roadblock in the questline).

**Comment by erenpal** [comment]
I am using 1.2.26 and task screen doesnt accepting water bucket on single or multiplay, it just opens task screen settings where we set tasks etc. I tried crounching but didint worked.

**Comment by ClockwiseGear** [comment]
I am also having this issue in single player. I found if I use the hopper that comes with the initial scren I can insert full buckets of water to add 1B at a tome, but it consumes the whole item.

**Comment by ghost** [comment]
I've decided to remove this chp 1 quest in 1.2.27, it seems like the mod has been changed so now you can only use pipes/automation to submit fluids
