### ISSUE TITLE
Cannot be installed on MultiMC- Blockcraftery DL error

### ISSUE THREAD

**Issue by luxidoptera** [al132mc/antimatter-chemistry#208]
Hi there, so I use MultiMC for modpacks and wanted to try this one out, but I can't seem to get it to install through MultiMC. There seems to be a problem with the version of Blockcraftery it's trying to install. For the record, I've installed several other CurseForge modpacks through the same method, and those have all worked fine.

![image](https://user-images.githubusercontent.com/15697751/68433454-8bbdbd00-0184-11ea-9655-c72f1da1e968.png)

I've yet to figure out a workaround for this problem, so I figured I would report it here. My apologies if this has already been reported.

**Comment by ghost** [comment]
Sorry for the (very) late response, but basically my advise is to just retry downloading

**Comment by ghost** [comment]
If you are still having issues make a new issue/re-open this one
