### ISSUE TITLE
[Suggestion/ Bug?] Crystal Glass (atum 2) not in blockGlass OreDict

### ISSUE THREAD

**Issue by R05A** [al132mc/antimatter-chemistry#209]
I have no clue whether or not this is intended, as the "Strange Sand " block (block that is smelted to make Crystal Glass) is in it's respective oredict (sand), but Crystal Glass is not in the blockGlass oredict

**Comment by ghost** [comment]
It does seem to be intended, as I specifically removed it in the script files. It's been over 6 months since I made the change so I can't totally remember why to be honest.. but i'm pretty sure it was due to some sort of recipe clash.
