### ISSUE TITLE
Silicon (NC) and Silicon Ingot (Alchemistry) have the same recipe

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#21]
![image](https://user-images.githubusercontent.com/24524662/57043380-a65c2a00-6c67-11e9-9f6d-08e0006578ee.png)
![image](https://user-images.githubusercontent.com/24524662/57043396-b116bf00-6c67-11e9-9ca2-d72ab18aec03.png)

**Comment by al132mc** [comment]
I just uploaded v0.5.3 fixing this, thank you.
