### ISSUE TITLE
[Suggestion] Reduce requirements for singularities for certain elements

### ISSUE THREAD

**Issue by lrwerewolf** [al132mc/antimatter-chemistry#217]
There are elements which have no way to make them other than fission/fusion (for one example, Oganesson).  Even with an array of 90 such machines, coming up with 5000 per singularity is extremely time consuming due to the slowness of the machines.

Given even the nether star singularity only requires 2000 stars per singularity, it would be reasonable for elements with no other means of manufacturing besides fission/fusion to require a lesser amount, perhaps 2500 or 3000.  The requirements could be raised back to 5000 or even higher if any of the suggested means for speeding these machines was implemented.

**Comment by MasterEnderman** [comment]
I tweaks some stats about the fusion and fission reactor as well as slightly decreasing the required elements for the singularities. We'll see how that works out.
