### ISSUE TITLE
[Crash] World no longer loads after returning from End (AE2 issue?)

### ISSUE THREAD

**Issue by Explodia** [al132mc/antimatter-chemistry#219]
Went back to the End today to train up an Enderdragon model. Jumped into the portal and the game crashed. (unending Loading screen) Restarted game, same problem.

Have previously gone to and from the End without incident (though I didn't have active RFT dimensions then...).

What little investigation I can do reveals that the crash logs point to locations of AE2 cables. Any chance there's a more elegant fix than Rip 'Em Out?

[crash-2019-12-27_14.52.19-server.txt](https://github.com/al132mc/antimatter-chemistry/files/4006470/crash-2019-12-27_14.52.19-server.txt)
[crash-2019-12-27_14.58.11-server.txt](https://github.com/al132mc/antimatter-chemistry/files/4006471/crash-2019-12-27_14.58.11-server.txt)
[crash-2019-12-27_18.29.37-server.txt](https://github.com/al132mc/antimatter-chemistry/files/4006472/crash-2019-12-27_18.29.37-server.txt)

**Comment by ghost** [comment]
Sorry for the late response. I'm not sure if this well help or not, but in config/forge.cfg there is a setting that looks like this
```
    B:removeErroringTileEntities=false
```
try setting that to true

**Comment by Explodia** [comment]
Looks like that's fixed it, though I can't yet find what it Removed... Many thanks!
