### ISSUE TITLE
Crash RFTools Builder-Draconium

### ISSUE THREAD

**Issue by Teppicymon** [al132mc/antimatter-chemistry#22]
RFTools dimension has draconium ore. There is a recurring crash when builder with silk touch quarry shapecard tries to mine it.

**Comment by al132mc** [comment]
Could I see the crash log please?

**Comment by Teppicymon** [comment]
ofc.
[crash-2019-05-04_19.57.15-server.txt](https://github.com/al132mc/antimatter-chemistry/files/3144775/crash-2019-05-04_19.57.15-server.txt)
ty

**Comment by al132mc** [comment]
Okay, thank you. I'll get the pack updated soon, though be aware that the intention is that draconium ore should not be mineable, even with silk touch. It shouldn't crash though, obviously

**Comment by Teppicymon** [comment]
Yeah, it says in the tooltip that there should be no drop as well as in another issue.
I installed a filter for the ore in the builder in the meantime. Just wanted to give you the heads up.

**Comment by al132mc** [comment]
Ok, this should be fixed in v0.5.6
