### ISSUE TITLE
[Bug] Quest progress gets reset on server for all player

### ISSUE THREAD

**Issue by DreiPixel** [al132mc/antimatter-chemistry#220]
so after my server was running fairly well with a daily reboot somehow the quest progress got reset except the Side quests.
this has now happened twice without any warning or crashes.

**Comment by ghost** [comment]
Very strange, also this is obviously a huge problem, but I haven't heard of this happening to anyone else, so it may be something on your end. Make sure that your server has enough memory space or weird corruption like this could potentially happen.
