### ISSUE TITLE
[Mod Suggestion] Beneficial mods to add

### ISSUE THREAD

**Issue by Phideault** [al132mc/antimatter-chemistry#222]
Hello!

I think you might be done with updating the pack, but if you're still doing it thank you for taking the time to read this! I have a few recommendations that i think would improve the pack just a tiny bit, without really changing the game play at all.

I recommend adding the Compact Machine Mod for the simple reason that it's a great way to save space on your base and that i think it helps a lot when it comes to keep stuff organized.

I also recommend adding the ConnectedTextureMod, simply because it makes the Fusion Reacor from NuclearCraft a bit prettier to look at. This one is a really minor add and not really necessary tho.

**Comment by ghost** [comment]
I added ConnectedTextureMod 2 days ago in v1.2.29, but I haven't decided yet whether or not i'll add Compact Machines in a future update.

**Comment by Phideault** [comment]
Yeah, i noticed that you added CTM!
As for CompactMachine, take your time to think about it, but if i may make a suggestion, maybe use CraftTweaker to change the recipes a little, i'm hovering JEI right now and i think Deep Mob Learning could have some potential for the recipes if we use the Corrupted Glitch Hearts to force the player to do some trials and explore a bit more of the mod. I know a bit about ZenScript, i could try to figure some recipes if you're interested?

**Comment by MasterEnderman** [comment]
There will be no further changes to the modlist.
