### ISSUE TITLE
1 fps in game

### ISSUE THREAD

**Issue by Fatonndev** [al132mc/antimatter-chemistry#224]
![image](https://user-images.githubusercontent.com/56699208/74592531-5ce09e00-5033-11ea-8258-50a218fbb0b9.png)

**Comment by ghost** [comment]
Can you confirm that you get a normal FPS with other modpacks?

**Comment by Fatonndev** [comment]
![image](https://user-images.githubusercontent.com/56699208/75471283-1419d500-59a3-11ea-8c31-32d300fbe222.png)
Found a rebuilt build, now playing with 200 + fps

**Comment by ghost** [comment]
Please only download the modpack from this page https://www.curseforge.com/minecraft/modpacks/antimatter-chemistry
