### ISSUE TITLE
[Suggestion] Add chemical combiner and dissolver recipes for cinnabar, made from mercury sulfide

### ISSUE THREAD

**Issue by supermattdab0ss** [al132mc/antimatter-chemistry#226]
TD;LR cinnabar is mercury sulfide, and there isn't a lot of easy ways to get it. There should be chemical combiner and dissolver recipes for cinnabar.

Long version is, thermal expansion has some very weird methods for ore processing, requiring you to make tectonic petrotheum, molten pyrotheum, and install various augments and catalysts in order to get to the theoretical maximum x4 ore processing, with a single ingot 100% byproduct or rich slag if there is no byproduct. In order to do this, you need cinnabar, which is essentially solidified mercury sulfide, and is available as a rare byproduct from redstone and gold ore, which is quite inconvenient if you want to use x4 ore processing on those ores instead of x3, like the lazy perfectionist I am. In reality, cinnabar is a mixture of impurities such as silicon, magnesium, and zinc oxides along with primarily mercury sulfide, and is usually used as an ore for elemental mercury. It's toxicity has been well documented as far back as ancient Rome, unlike lead. however it's most common use was a red dye, hence why rose red dissolves into mercury sulfide, which is already present in the game. Adding the recipes to make a single piece of cinnabar out of 8 mercury sulfide would allow much easier maximum ore processing, and is a realistic recipe to add.

Thank you for coming to my Ted Talk.

**Comment by MasterEnderman** [comment]
https://github.com/Dark-Arcana/antimatter-chemistry/pull/229
