### ISSUE TITLE
broken recipe for apples - pack version 0.5.6

### ISSUE THREAD

**Issue by Quinnplaysgamestv** [al132mc/antimatter-chemistry#23]
the chemical combiner recipe for apples appears to make spruce logs instead of apples

**Comment by al132mc** [comment]
Please use the lock recipe functionality in JEI (the [+] button) while you have the Chemical Combiner GUI open to prevent this from happening. Please let me know if you continue to have trouble or can't figure out what i'm referring to.

**Comment by al132mc** [comment]
Actually, here, I recorded a quick demonstration for you

[Video](https://imgur.com/0DjOBbD)

**Comment by al132mc** [comment]
Please comment if you are still having issues
