### ISSUE TITLE
Fission Reactor doesn't start

### ISSUE THREAD

**Issue by SirGeremiah** [al132mc/antimatter-chemistry#232]
Okay, this might be entirely me missing something, but I've done all the research I can figure out how to do. I have a completed fission reactor, and put fuel in it. Nothing happens - no progress, no RF produced, nothin'. I looked back at Nuclearcraft wiki, and it shows use of a fuel rod, which appears not to be included in this pack. I'm at a loss.

**Comment by ghost** [comment]
Give the controller a redstone signal

**Comment by SirGeremiah** [comment]
That was it. Thanks!
