### ISSUE TITLE
Cursed Earth not spawning mobs quickly

### ISSUE THREAD

**Issue by TheDeejster** [al132mc/antimatter-chemistry#234]
I got the cursed earth, and tried to use it to make a mob farm but mobs aren't spawning on it. The cursed earth is in complete darkness, and is a 3x3x3 space, and mobs spawn very infrequently. Unless this is intended behavior or user error, something's wrong.

**Comment by MasterEnderman** [comment]
Just build a bigger Mobfarm if you want a higher spawnrate.
