### ISSUE TITLE
[CRASH] creating compressed cobblestone crashes the game

### ISSUE THREAD

**Issue by KingofJupiter** [al132mc/antimatter-chemistry#235]
So the game crashes every now and then when I try to create compressed cobblestone. It will work for a little bit but then the game eventually crashes.

Error: java.lang.NullPointerException: at index 0

**Comment by ghost** [comment]
Duplicate of https://github.com/al132mc/antimatter-chemistry/issues/161 . For compressed cobble use a vanilla crafting table or your AE2/RS system, for some reason it crashes with the tinkers workbench
