### ISSUE TITLE
Upgrading cobblestone generator

### ISSUE THREAD

**Issue by Rowanfalar** [al132mc/antimatter-chemistry#237]
I was trying to upgrade the Tier one cobblestone generator to the Tier two (iron) and it would not craft. I tried in the vanilla crafting table as well as the Tinker's crafting station. I also made a new Tier one just in case it needed a fresh one. Still did not craft in either crafting table. Please fix.

**Comment by ghost** [comment]
If you look carefully you'll notice that some of the cobblestone generators are created in the chemical combiner because the recipes use more than 1 count of an item in a single slot which is impossible to do in a crafting table.
