### ISSUE TITLE
Game crushed while opening the last page in the creative mode inventory

### ISSUE THREAD

**Issue by neyc314** [al132mc/antimatter-chemistry#238]
Game crushed while opening the last page in the creative mode inventory.

The position of the mouse when the error happened(A part of the crash-report)

> -- Screen render details --
> Details:
> 	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
> 	Mouse location: Scaled: (509, 134). Absolute: (1019, 718)
> 	Screen size: Scaled: (840, 494). Absolute: (1680, 987). Scale factor of 2

Following are the crash-reports:

[crash-2020-04-20_15.37.46-client.txt](https://github.com/al132mc/antimatter-chemistry/files/4506733/crash-2020-04-20_15.37.46-client.txt)

[crash-2020-04-20_15.40.04-client.txt](https://github.com/al132mc/antimatter-chemistry/files/4506737/crash-2020-04-20_15.40.04-client.txt)

**Comment by MasterEnderman** [comment]
Doesn't happen in the current version (1.2.36)
