### ISSUE TITLE
[Suggestion] Replace Blockcraftery with ArchitectureCraft

### ISSUE THREAD

**Issue by dallenforth** [al132mc/antimatter-chemistry#240]
Hello, as someone that loves to build, I find myself quite frustrated with the limitations posed by Blockcraftery. The mod lacks many of the shapes necessary for connecting to itself. Example: https://i.imgur.com/qCLxn5D.png
Seemingly the only advantage that this mod has is the ability to create textures doors, trapdoors and pressureplates

For building, ArchitectureCraft is far superior as it has significantly more shape options and placement orientations than Blockcraftery.

https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev

**Comment by MasterEnderman** [comment]
The modlist for the pack is already complete.
