### ISSUE TITLE
Game freezes every time I try to enter the deep dark dimension

### ISSUE THREAD

**Issue by ezra1029** [al132mc/antimatter-chemistry#242]
[Crash log](https://github.com/al132mc/antimatter-chemistry/files/4826261/New.Paste.1.txt)
Hi, I'm not familiar with reporting this kind of issue so apologies if I'm missing something obvious or doing something wrong - please let me know if so.
I've tried quite a few times, but every time I try to enter the deep dark dimension through a portal, the game freezes until I kill it.

**Comment by MasterEnderman** [comment]
duplicate of #161
