### ISSUE TITLE
Fusion Controller stage unlock

### ISSUE THREAD

**Issue by JennaZoo** [al132mc/antimatter-chemistry#244]
I've completed the nether star quest but the fusion controller recipe is still unavailable.

**Comment by JennaZoo** [comment]
Tried /gamestage add jennazoo fusion, which gave the message 'You've unlock stage fusion!' But the fusion controller recipe is still locked.

**Comment by JennaZoo** [comment]
Used creative to get controller but recipe is still locked.

**Comment by OniyaMCD** [comment]
The correct command is listed in this comment.  
https://github.com/al132mc/antimatter-chemistry/issues/227#issuecomment-590723459

**Comment by JennaZoo** [comment]
The recipe is now available, Thank you!
