### ISSUE TITLE
Tinkers Construct Gear Cast using 2 Brass?

### ISSUE THREAD

**Issue by MonfGeiger** [al132mc/antimatter-chemistry#249]
In all the time I used TC, the aluminum brass alternative was meant to be able to make any cast that used 2 gold with only one ingot of brass....yet, when I went to make the gear casts for thermal gears, the cast-making cost with brass is two ingots, the same as gold.

I get that enough materials on either side erase this, both gold chemicals and the aluminum and copper chemicals, but its been set in stone: brass only uses 1, gold uses 2. Is this a config goof, or an actual bug in the modpack itself, or purposefully intended?

**Comment by ghost** [comment]
I don't recall this being something I tweaked at all, but i'll just say it's intentional.
