### ISSUE TITLE
Crash- pulverizer and redstone furnace

### ISSUE THREAD

**Issue by Korono22** [al132mc/antimatter-chemistry#25]
Hello, my world is corrupted ( crashes every time i go into save ). I connected pulverizer and redstone furnace together, put hopper on top of pulverizer and iron chest on top of redstone furnace. When i started putting ores in hopper the world crashed and i cant get into it anymore. 
Heres the crash log: https://paste.dimdev.org/avaxanizaw.mccrash

**Comment by al132mc** [comment]
Were you using a "Speedy Hopper" or a regular vanilla hopper?

**Comment by al132mc** [comment]
Okay, could you try removing the Speedy Hopper mod and see if that helps?

**Comment by Korono22** [comment]
Well, it worked. Should i play the pack with the speedy hoppers disabled or what?

**Comment by al132mc** [comment]
For right now, yes. Speedy Hoppers is my mod though, so I will try and figure out what is wrong as soon as I can

**Comment by al132mc** [comment]
We talked earlier on Discord, and you believe this is fixed after updating
