### ISSUE TITLE
Quests overlapping and one is hidden behind other and inaccessible.

### ISSUE THREAD

**Issue by vishalkotwar** [al132mc/antimatter-chemistry#252]
![Annotation 2020-10-19 055648](https://user-images.githubusercontent.com/39226511/96390111-b3106d00-11d0-11eb-840a-bba64fb427d6.jpg)
I cant see the fishing rod quest!(when I click it, only the wart quest comes up and not the fishing rod one.)
Also the zombie killing quest is hidden.( when i click it, the zombie quest opens only, not the one for green antimatter.)
the arrows are all messed up.
I do not know what is causing the issue. I tried changing the GUI scale, Zoom in/out, Change game window size. Nothing works. Using the latest Beta version on curseforge.

**Comment by ghost** [comment]
It looks like you are using a very outdated version. The most recent version is a release version released on May 20, **2020**. You are probably using the beta version released on May 17, **2019**. Your version is **35 versions out-of-date**
