### ISSUE TITLE
[Mod Suggestion] Torchmaster

### ISSUE THREAD

**Issue by MonfGeiger** [al132mc/antimatter-chemistry#253]
This modpack has been a....challenge to play, but a rewarding one all the same. It also needs a mob farm, and the best way for that is the cursed earth method. Thing is: mobs will forever keep spawning on cursed earth farms, and what if we want to turn it off temporarily to increase storage and such? Unless a method already exists in antimatter chemistry that the server admins haven't closed off yet, only other way I now if the torchmaster mod and from it: the mega torch, which stops all entity spawning in a certain radius around it.

Request that by the next update to AC that the torchmaster mod be added to the pack

**Comment by Wishbone1977** [comment]
I don't know if cursed earth has been changed from the way it used to work in general, or if it is a change specific to this modpack, but in this one at least, cursed earth stops spawning mobs when it is in sunlight, but doesn't burn and revert back to normal dirt.

Hence, my mob farm is underground in the antimatter dimension, with a roof of a single layer of cobblestone. When I need to switch it off, I simply vein mine the cobblestone roof. That stops the mobs from spawning without damaging the farm itself. I could probably do something clever with pistons to be able to open and close the roof at will, but it's so rare that I need to stop it that I haven't bothered so far.

**Comment by MasterEnderman** [comment]
There won't be any additions to the modlist anymore.
