### ISSUE TITLE
windows server crash (tick central mod)

### ISSUE THREAD

**Issue by S0Y3S** [al132mc/antimatter-chemistry#258]
latest working version off antimatter chemistry server is 1.2.29 since there is no server for 1.2.30 but ever since
1.2.31
1.2.32

the server has been crashing on startup which is duo to tickcentral which i just removed on my own to get the server to  work.
so if  u aint gonna remove it at least let people know that "tick central" crashes if u try the server on windows machine

**Comment by MasterEnderman** [comment]
TickCentral was removed from the pack ages ago -> closing
