### ISSUE TITLE
Template Missing Blocks

### ISSUE THREAD

**Issue by jlaw21** [al132mc/antimatter-chemistry#26]
When starting a new game using the STandard Template:
![image](https://user-images.githubusercontent.com/38250705/57381643-50ace380-7179-11e9-98f2-3f6c9fa54625.png)

**Comment by al132mc** [comment]
This is okay, you can click yes and play, but I will fix this in the next version

**Comment by al132mc** [comment]
This was fixed earlier today in 0.5.9, closing
