### ISSUE TITLE
Seeds break by themselves when holding shift

### ISSUE THREAD

**Issue by Impxrtant322** [al132mc/antimatter-chemistry#261]
Title is self explanatory. I placed down a growth crystal tier 2 in my farm, replacing the water source block with it, and all of the sudden there are 4 spots where seeds will just keep breaking themselves after a few seconds and theres an area in the middle where seeds will not grow at all as they are not affected by holding shift.
Im unsure how to fix this, and I attempted to replace the block several times to no success.

Logs show absolutely nothing

I've tried:

- Replacing the dirt block
- Breaking growth crystal
- replacing growth crystal with water source block (still has same effects)
- replacing dirt block with different block
- growing the seed with bone meal (will randomly break again after a few seconds)

Pictures:
Red shows the blocks where seeds are breaking themselves
Blue shows the blocks where seeds do not grow even while holding shift
![image](https://user-images.githubusercontent.com/63988752/98189253-ceb68b80-1ed1-11eb-946e-8d80ab017535.png)

**Comment by Wishbone1977** [comment]
There _is_ something odd going on with the growth crystals. I put one down underneath my cactus farm, but I had to put it two blocks down to get it to work. If I put it just one block down, I couldn't place sand on top of it. The sand block would break into item form as soon as it was placed down. I thought it was weird, but didn't think much of it, as the crystal should still work fine lower down (precise depth depending on the tier of the crystal).

**Comment by MasterEnderman** [comment]
the random seed breaking can't be reproduced in the newest version of the pack.
as far as the sand breaking goes. this happens to all gravity affected block in the game, when they are placed right above a growth crystal. so i guess you can call it a special 'feature' for now as the 1.12 version of tiny progressions is no longer maintained.
