### ISSUE TITLE
Not detecting steel ingots

### ISSUE THREAD

**Issue by will-younes** [al132mc/antimatter-chemistry#268]
I've tried everything I can think of but it still isn't detecting them.
I tried making them in different ways, relogging. putting them in a chest, putting them in a chest and relogging, and even getting them from JEI.
Other people have had the same problem but no explanation to fix it.

**Comment by Dr-Game** [comment]
The Steel ingot quest is not an auto-detect quest. This quest consumes all 48 steel ingots, and you must submit the quest by going into the questbook, clicking on that quest, and manually clicking "Submit" with the steel ingots in your inventory.
