### ISSUE TITLE
RFTools Dimensions Receiver

### ISSUE THREAD

**Issue by Bunnycube** [al132mc/antimatter-chemistry#269]
The RFTools Dimensions receiver is not automatically generating whenever you make a dimension.

**Comment by mouseas** [comment]
Does this happen every time, or just occasionally? I have it happen occasionally where it generates but for some reason doesn't show up in the dial list, but about 95% of the time it works correctly for me.

**Comment by Bunnycube** [comment]
I generated 5 dimensions in my main world, none worked, then I generated 2 in another, which failed too. In short, it happens every time.
