### ISSUE TITLE
Milk and Magnesium fluids have no texture

### ISSUE THREAD

**Issue by mouseas** [al132mc/antimatter-chemistry#272]
![magnesium-no-texture](https://user-images.githubusercontent.com/1171633/100551514-4ca25400-323e-11eb-8cfd-ab77c1e14f79.png)
Fluids for Milk and Magnesium have no texture in the world.

**Comment by OniyaMCD** [comment]
This is a config setting in NuclearCraft.  You can turn the textures back on if you like - the pack is small enough that it won't cause problems. hit Mod Options, and then the Nuclearcraft mod/Config/Other Configs and find Register Fission Fluid Blocks.  You may have to close out to the main menu and then load your world again.
