### ISSUE TITLE
Chapter 3 Magnesium ingot.

### ISSUE THREAD

**Issue by Pyrofox72** [al132mc/antimatter-chemistry#275]
I have tried many different ways of making magnesium ingots for the chapter 3 quest pertaining to the quest "Device Frame Components".  No matter what I have tried such as logging in and out of the game, making the ingots multiple times and in many different ways, etc. but none of this seems to fix the issue so if you could please help me fix this that would be greatly appreciated

**Comment by OniyaMCD** [comment]
Please verify if the quest is looking for Magnesium Ingots (element 12, symbol Mg) or Manganese Ingots (element 25, symbol Mn)

**Comment by Pyrofox72** [comment]
It is asking for either Magnesium ingots from Antichemistry or nuclearenergy mod. but the only thing i'm able to get is the one from nuclearenergy

**Comment by Pyrofox72** [comment]
I completely read the quest wrong and it was Manganese not magnesium
