### ISSUE TITLE
How to spawn in a single player default world

### ISSUE THREAD

**Issue by tylerroost** [al132mc/antimatter-chemistry#280]
I understand the point of this mod is to spawn in the antimatter world, but I would like to know how to spawn in the default worldtype in a single player world

**Comment by ghost** [comment]
I encourage people to play the pack as designed for managing bugs and things, but obviously people can play however they want. Anyway, ``config/HardcoreMapReset.cfg`` change the line ``B:"Show Create World Button"=false`` to true then restart the game

**Comment by tylerroost** [comment]
Thanks for an amazing quick response
