### ISSUE TITLE
Fluid pump

### ISSUE THREAD

**Issue by Coolerdiamonds9** [al132mc/antimatter-chemistry#282]
The fluid pump keeps having problems where it just randomly stops working and even if I go into creative to fix it, I just can't get it to work for like 10 mins. Is this an intentional feature to stop infinite power gen?

**Comment by Coolerdiamonds9** [comment]
Any ideas?

**Comment by ghost** [comment]
I don't recall hearing about this happening to other people.. What mod is the fluid pump from?

**Comment by Coolerdiamonds9** [comment]
Industrial foregoing

**Comment by Coolerdiamonds9** [comment]
Sometimes it just shuts off even with source blocks around it and range upgrades big enough, plus lots of power for it and it’s not paused

**Comment by ghost** [comment]
The mod hasn't been updated for 1.12.2 in quite a while and probably won't ever be again, so my suggestion would be to use an alternative pump if possible. The RFTools builder should be able to pump fluids if you are trying to pump mass amounts of fluid in-world (i.e. lava or RFTools dimensions). If you are just trying to pump water then you can use the aqueous accumulator from Thermal Expansion

**Comment by Coolerdiamonds9** [comment]
Ok
