### ISSUE TITLE
Server dont start

### ISSUE THREAD

**Issue by XiNaru** [al132mc/antimatter-chemistry#285]
with the prefabricated world in the single player, the server does NOTHING

a normal map he starts sooooo normal.
but if I then take the regular, pre-made one, the server hangs up when it starts and nothing works.

so please insert generator settings. with the ready-made world this only works in single player.

**Comment by ghost** [comment]
This sounds like it could be an issue of limited specs/resources on your server computer. Have you been able to run any other modpacks successfully on this server?

**Comment by ajarodiy** [comment]
I have experienced the same issue, and it was not due to the specs of the server. I had to contact my server host and they mentioned something about a mod being missing or something.
Here is a console log from when it was not working: https://pastebin.com/ZiNxHvGp
