### ISSUE TITLE
Smelting quest wont end even though i have all the required items

### ISSUE THREAD

**Issue by Some-guy476** [al132mc/antimatter-chemistry#290]
It shows all the items needed for the quest as obtained but will not let me take the rewards or complete the quest.
![image](https://user-images.githubusercontent.com/80173126/125837250-a7207ccd-ce25-43df-8510-2eeb337e7195.png)

**Comment by OniyaMCD** [comment]
1) It looks like you're using an older version of the pack, as I just installed it and the quest tree looks somewhat different.
2) The Seared Tank isn't checked off.  Make sure that is in your inventory and attempt to complete the quest again.

**Comment by Some-guy476** [comment]
Thanks, I did not notice that I did not have the tank since it did not seem to register it when it was partially full
