### ISSUE TITLE
Missing element singularities 

### ISSUE THREAD

**Issue by WittyPlaceholder** [al132mc/antimatter-chemistry#293]
Most of the singularities (likely the one for the elements) are missing

![missing elements]( https://user-images.githubusercontent.com/53082631/129495883-fe17ba3e-7db6-4a4a-80c3-d6a0396fb95e.png)

Any ideas on what is wrong or how to fix it, or is it a bug?

**Comment by OniyaMCD** [comment]
Sounds like the CraftTweaker scripts didn't run properly.  Where did you download the pack from?

**Comment by WittyPlaceholder** [comment]
It was downloaded from the curseforge installer

I also just uninstalled and reinstalled the pack and the problem persisted

**Comment by OniyaMCD** [comment]
Check your 'singularities.cfg' file with a text editor and verify that the elemental singularities exist there.  Also, check the date that file was last modified.

**Comment by WittyPlaceholder** [comment]
thank you that has fixed it
