### ISSUE TITLE
Overworld Apple crashes game

### ISSUE THREAD

**Issue by ghosthacker478** [al132mc/antimatter-chemistry#295]
Whilst trying to make foods that i can eat for more health, i came across the overworld apple, crafted it, and attempted to eat it, and it proceeded to crash the game, probably because the overworld doesn't exist. The overworld apple should probably just be disabled from crafting

**Comment by DeltaEpsilon7787** [comment]
The overworld is the antimatter dimension. Provide a crash log please.

**Comment by MasterEnderman** [comment]
Recipe will be disabled.
