### ISSUE TITLE
can't start server

### ISSUE THREAD

**Issue by talan902** [al132mc/antimatter-chemistry#297]
ok so, whenever i try to start my server i get an error message saying "JavaVersionOrPathError" i haven't touched the code, this is my first time making a server, can you help? thanks!
-talan902

**Comment by aaronhance** [comment]
I had same issue, disabling java check gets past it but then spammed with invalid arguments, after removing them there are java errors. Does this pack only run on a very specific version of java? All other packs are running fine.

**Comment by MasterEnderman** [comment]
There have been some updates to the pack as well as to the server files. Please try the latest version and report back. :)
