### ISSUE TITLE
Extra utilities compressed cobblestone possible crash?

### ISSUE THREAD

**Issue by ciclon5** [al132mc/antimatter-chemistry#299]
While doing the deep dark portal quest doing all the compressed cobblestone i noticed that at random the game apparently crashed (it crashed on me twice on the whole quest). After digging around the error message i noticed that the crash was tied to a "render" error with the compressed cobblestone block. The crash was random as it did not happen every time i opened my inventory it just happened randomly when opening an inventory with compressed cobble in it (just single compressed other variations like double and triple do not crash the game), its like a chance thing.

**Comment by ghost** [comment]
Known issue see https://github.com/al132mc/antimatter-chemistry/issues/161
