### ISSUE TITLE
Draconium Ore can spawn in the Deep Dark

### ISSUE THREAD

**Issue by al132mc** [al132mc/antimatter-chemistry#3]

**Comment by Chalky123b** [comment]
Draconium ore also spawns in RFtool worlds, and Draconium dust generates from Quantum Quarries.

**Comment by al132mc** [comment]
I don't mind Draconium being in RFTools Dimensions, ideally that's around the earliest they should be able to acquire it, but I think the Deep Dark is too soon. I haven't decided quite how i'm going to deal with it yet. I could probably add a custom mod that tweaks it out, but i'm not sure yet.

**Comment by al132mc** [comment]
Fixed in 0.4.20. Ores will still spawn, but they will have no drops, even with silk touch
