### ISSUE TITLE
Unable to join server when connecting from a pack downloaded from curseforge or GDLauncher but packs downloaded from multimc work

### ISSUE THREAD

**Issue by BoxC4T** [al132mc/antimatter-chemistry#301]
![image](https://user-images.githubusercontent.com/74559314/148866765-528446d3-6a55-4646-a7de-e350f6889f69.png)

**Comment by Technous285** [comment]
I experienced this same issue trying to use version 1.2.34 of the pack to play on Gaming on Caffeine's server and found that for whatever reason GDLauncher isn't pulling those two mods from CurseForge along with the rest of the pack.
It is possibly a problem with GDLauncher as those 2 mods in question are classed as "abandoned" by CurseForge and won't show up in GDLauncher's menus when you go "Add Mod" to add the mods to the pack manually.

**Comment by MasterEnderman** [comment]
Same Problem as #305 . Old mods getting archived by curseforge and can no longer downloaded by a launcher (GDLauncher/Curseforge/MultiMC) instad you have to download the mods manually and add them to the pack. Nothing we can do about it.
