### ISSUE TITLE
Deep Dark Portal Not Activating.

### ISSUE THREAD

**Issue by JTyrranax** [al132mc/antimatter-chemistry#302]
I'm trying to complete Chapter 2 in the quest book, but have run into a soft lock. I've managed to craft the Deep Dark portal, but when I place it and try to rightclick it to teleport, nothing happens. No crash, no error pop up. I've attempted to try the solution for the uncraftable seared faucet issue, but it still soft locks me as I can't get the ores without going into creative.

**Comment by SilverhuntX** [comment]
Stand on top of it and stay there til it activates, then get off once you are in the DD

**Comment by JTyrranax** [comment]
I'm also watching a playthrough, and they just got to it. Thank you for the answer.
