### ISSUE TITLE
Missing Mods when installing Pack  (Curseforge/GDLauncher/MultiMC)

### ISSUE THREAD

**Issue by MMLukeDraper** [al132mc/antimatter-chemistry#305]
Hey, I am new to the pack. Loaded up the Skyblock version of the pack for the first time and I got these messages, which persisted even if I made a new world or reinstalled the pack. 

![image](https://user-images.githubusercontent.com/26820674/164068912-41d7aa6f-37a9-4007-88da-46df95d3635b.png)
![image](https://user-images.githubusercontent.com/26820674/164068938-f0dd0a1e-0eb4-460f-8e2a-a1f94718e6ef.png)

After speaking with some peeps on the Alchemistry Discord, it seems to just be due to the Earthworks mod not being downloaded by the launcher. I am using GDLauncher if that makes any difference also. 

Thanks.

**Comment by MasterEnderman** [comment]
After doing some research it turns out that the Earthworks mod was archived on curseforge as it's no longer maintained. I'm already working on a fork of it to release it again. After that it will replace the Earthworks version currently used in the pack.

**Comment by MasterEnderman** [comment]
Earthworks should no longer be a proplem with the next version as we switch to a maintained version of earthworks.
https://www.curseforge.com/minecraft/mc-mods/earthworks-extended-life
This leaves ExtraCells2 on the table.

**Comment by MasterEnderman** [comment]
Great news. Someone forked ExtraCells2 to keep it alive. So the "missing" mods bug should be fixed with the next version. (at least for now)
