### ISSUE TITLE
Suggestion:  Silverfish blocks should drop protein

### ISSUE THREAD

**Issue by OniyaMCD** [al132mc/antimatter-chemistry#308]
While mining in an RFTools dimension, I encountered some silverfish blocks, and cleared them out of my way with a silk-touch pick.  On a whim, I ran them through a dissolver and found that they actually processed (apparently as regular stone).

Thought it would be funny if it actually produced something 'insect related'.

**Comment by MasterEnderman** [comment]
FunFact: I'm not able to put the "Monster Egg" stone blocks in the dissolver as there isn't a recipe for them in the first place. So it's quite interessting that you got that working. (I'll still add the additional recipes)

**Comment by OniyaMCD** [comment]
It turns out that the Silk Touch turns the Silverfish block back into regular Stone, so the Monster Egg may not be obtainable.

**Comment by MasterEnderman** [comment]
That would explain why I was unable to put them into the dissolver... Probably keep the recipe anyways if the player obtains them somehow.
