### ISSUE TITLE
Game stopped working.

### ISSUE THREAD

**Issue by leosu950** [al132mc/antimatter-chemistry#309]
I opened crafting grid and change the sorting type to inventory tweaks then game stopped working.

**Comment by MasterEnderman** [comment]
Could we get a crash report or log file of some sort? without them it would be nearly impossible to help you.

**Comment by leosu950** [comment]
There isn't. It just froze. Until I close it.

**Comment by MasterEnderman** [comment]
Then there is nothing we can do to help you narrow down the problem.
