### ISSUE TITLE
Server Installation not working

### ISSUE THREAD

**Issue by aglasencnik** [al132mc/antimatter-chemistry#310]
Hi, I want to install this modpack on my cloud linux server.
I unzipped the server pack, and with filezilla transfered files to the directory I created on the server.
In there I tried the folowing command like the readme.md guide told me to: sudo bash ServerStart.sh
I got an error that said: ServerStart.sh: line 143: cd: ServerStart.sh: Not a directory
Can anyone please tell me what do I have to do to get the server working.
Thanks

**Comment by Timbroglio** [comment]
Hello! You shouldn't need `sudo bash` - can you try just using just `bash ServerStart.sh` from the directory? That line is making sure you're running from the correct directory, so you'll want to cd into that directory (which should contain all the files from the server .zip, and no others) and then run `bash ServerStart.sh`.

**Comment by aglasencnik** [comment]
Hi! I managed to get it working with just running the forge install file and then starting the server manually.
