### ISSUE TITLE
A Skyblock and Default World combine together when create a world using "Default Template World" 

### ISSUE THREAD

**Issue by Krixiz** [al132mc/antimatter-chemistry#312]
It was not normal because on Skyblock template, you started with this pillar and a void.
This one is a default one, already tried to delete the world and create a new one using the same template.

POV when it was created.
The video resolution was bad because it was compressed.

* The world that was in the video and picture was not the same world.

![image](https://user-images.githubusercontent.com/50483551/167519329-025050f2-7004-4447-a0e6-d909e4263aee.png)
![image](https://user-images.githubusercontent.com/50483551/167519337-9066768f-da9e-49b0-90c3-21b0827c202e.png)

https://user-images.githubusercontent.com/50483551/167519672-d81181de-b65d-4fac-a7d7-59ea4d950a5f.mp4

**Comment by MasterEnderman** [comment]
Sorry for that. guess I haven't tested the new world generation enough. However I replaced the mod to generate the void world (again). So this should no longer be an issue in v1.3.1 (once it's released)
