### ISSUE TITLE
[Bug]? no mobs spawn for me at all only spawner blocks spawn mobs

### ISSUE THREAD

**Issue by GermanPITA** [al132mc/antimatter-chemistry#314]
no mobs spawn for me in the nether only blazes from spawners nothing else spawns for me

**Comment by GermanPITA** [comment]
just tried making a darkroom spawner in the overworld and nothing is spawning in there either im in normal mode and i cant advance without pigmen

**Comment by OniyaMCD** [comment]
Darkrooms in the overworld will not spawn mobs.  Mobs should be spawning in the nether, though.  Might take a day or two before the devs can check this out.

**Comment by GermanPITA** [comment]
well ive made multiple worlds and all of them no mobs spawned

**Comment by Roguim** [comment]
Are mobs still spawning from spawners though?

**Comment by GermanPITA** [comment]
yes in every single world

**Comment by OniyaMCD** [comment]
Mobs will spawn from spawners and cursed earth.  They SHOULD spawn naturally in the nether.  They WILL NOT spawn naturally in the overworld.  It's only been 2 hours since you reported the bug, and the devs will need to look to find out why they are NOT naturally spawning in the nether.

**Comment by GermanPITA** [comment]
im not expecting an immidiate solution just trying to help by reporting bugs i find

**Comment by MasterEnderman** [comment]
I have an idea what's causing that. Probably something with the game rules I set when a new world is created.
