### ISSUE TITLE
Hang Glider has weird sounds

### ISSUE THREAD

**Issue by RefaelNesss88** [al132mc/antimatter-chemistry#316]
When I am gliding with the Hang Glider, it makes an annoying beep sound. it does it sometimes and sometimes doesnt even have any sound.

**Comment by MasterEnderman** [comment]
Check your controls, there is a key bind to disable the sounds:
![image](https://user-images.githubusercontent.com/24524662/167648228-6964d237-434c-4321-b90e-aacb2941c3a8.png)
