### ISSUE TITLE
Alchemistry ingots are superceding ingots from other mods, breaking recipes.

### ISSUE THREAD

**Issue by OniyaMCD** [al132mc/antimatter-chemistry#317]
The recipe for the scarab requires a Thermal Foundation Platinum Ingot, but the combiner creates the Alchemistry Platinum ingot, which doesn't function.  Ingots from other mods are also not ore-dicted with Alchemistry ingots, causing recipes to break.

**Comment by MasterEnderman** [comment]
Totally forgot to replace the scarab recipe with an OreDict instead of the hardcoded item.

Which other recipes break with the alchemistry ingots?
