### ISSUE TITLE
I cant open Antimatter Chemistry v1.3.1

### ISSUE THREAD

**Issue by RefaelNesss88** [al132mc/antimatter-chemistry#318]
when i change to Antimatter Chemistry v1.3.1, it said below smth like "An error or more occurred" and i cant open the version.

**Comment by MasterEnderman** [comment]
Which launcher do you use? (I released v1.3.2 a few minutes ago. The problem shouldn't be related to that, but try updating to that version instead.)

**Comment by RefaelNesss88** [comment]
CurseForge v0.195.2.1

**Comment by MasterEnderman** [comment]
Maybe try updating to a newer version? (I'm using v.0.196.1.11) Or try to restart the app (This sometimes fixes issues with downloading mods / modpacks)

Quick side note: the newest version is now v1.3.3 not v1.3.2 (had to release a hotfix)

**Comment by MasterEnderman** [comment]
@RefaelNesss88 any updates? Is the pack working for you now?
