### ISSUE TITLE
Materials required for certain quests in chapters 4 and 6 possibly unnecessary/could be substituted

### ISSUE THREAD

**Issue by myleszey** [al132mc/antimatter-chemistry#32]
Skeleton and Creeper Spawn Eggs aren't necessarily required to increase the levels of their respective data models, since it's possible to craft the Drop of Evil as early as Chapter 2 and both skeletons and zombies can be found on the Deep Dark's surface relatively uncommonly.
Also, Wither Skeleton Skulls can be substituted with 4x Wither Dust, which drops much more commonly from wither skeletons, to produce the same amount of Mendelevium without the need to get a 2% chance drop.

**Comment by al132mc** [comment]
Fixed in 1.1.1, thank you
