### ISSUE TITLE
Sky is Black

### ISSUE THREAD

**Issue by SGamer777** [al132mc/antimatter-chemistry#322]
My worlds sky is blue well normal, but i enter a new world sky is black. i want it's white as blue like normal world sky

**Comment by MasterEnderman** [comment]
With the last update the biome of the antimatter dimensions was changed to the_end instead of the normal plains biome. That causes the sky to turn darker.
Because the biome is set on world generation it only affects worlds created after the update and isn't re-applied to older worlds.
