### ISSUE TITLE
Warp Glitch?!

### ISSUE THREAD

**Issue by IntenseScoutHD** [al132mc/antimatter-chemistry#325]
Hello developers, 
I dont know how to discribe it but i just found a concerning bug in the antimatter chemitry modpack. So i opened it via curseForge, as always, and found a really interesting bug. Upon opening my world nothing directly happens, but if i try to move, my game just completely goes wild and is moving really interesting. also i go supersonic and after a while my game just completely crashes.
so thas the best i can describe it. And before i forget about it, this bug happened after the newest patch

![Bild_2022-05-28_120334156](https://user-images.githubusercontent.com/95529729/170820630-51aee6d0-1e05-459f-8970-c7baf329d434.png)

**Comment by IntenseScoutHD** [comment]
okay a short video here:

https://user-images.githubusercontent.com/95529729/170820728-8e9a5824-4b96-443e-9b70-951cd8a87abd.mp4

**Comment by MasterEnderman** [comment]
Could you send us your Crash Report? Otherwise we won't be able to track down what causes this behavior.

**Comment by IntenseScoutHD** [comment]
Uhm okay there is a problem -_- I was not able to recreate the crash
Szenario... And the original crash code i have not written down. Can i
somehow see recent crash reports after closing them?

MasterEnderman ***@***.***> schrieb am Sa., 28. Mai 2022,
21:16:

**Comment by OniyaMCD** [comment]
There should be a folder of crash reports in the Instance folder for your launcher.  They're organized and identified by date.
