### ISSUE TITLE
Draconic Evolution Explosions

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#328]
We love our server and it bypasses the chunk claiming. So it's time to tone them down.

**Comment by Tetrik82** [comment]
For some more detail, the draconic evolution reactor deletes blocks in claimed chunks, regardless of what chunks are claimed and who the chunks are claimed by. The explosion essentially continues normally, removing huge swaths of land. Another issue with it is that the server can't calculate even a half-strength reactor explosion, and completely crashes. There is nothing special that has to be done for this to occur; it's just simply causing the reactor to meltdown as it generally does.
