### ISSUE TITLE
Server: broken settings.cfg 

### ISSUE THREAD

**Issue by tilda** [al132mc/antimatter-chemistry#33]
The settings.cfg included in server files (latest version 1.1.0) have semicolons at the end of each line which does not work for the server script (at least on Linux). This leads to the server script trying to grab the wrong file from the Forge file server and failing.

**Comment by al132mc** [comment]
Hm, strange. I am just using the scripts from [here](https://github.com/AllTheMods/Server-Scripts) which are deployed widely, and I assume should work on linux as that's what most servers probably use. I don't know enough about bash to immediately be useful though.

**Comment by tilda** [comment]
Weird, because the same scripts worked on my other servers (i.e. Enigmatica 2 Light). I checked the settings.cfg for that and it has semicolons in it (and worked at the time I used it), so not sure what's wrong here.

**Comment by al132mc** [comment]
In 1.1.1 (and 1.1.2+) I re-downloaded the files just to make sure they are accurate. If you are still hosting the server let me know if the server scripts work for you in more recent versions.

**Comment by al132mc** [comment]
This has been fixed for the last few weeks now
