### ISSUE TITLE
Replace quest Creative ME storage cell with vending upgrade

### ISSUE THREAD

**Issue by mtbrenner** [al132mc/antimatter-chemistry#333]
While this is the creative item you should make first to get infinite amount of items, it lets you create any item from JEI not just the ones you already have (drag from JEI into cell workbench). The vending upgrade would be a safer option in that it can only give items infinitely which you put in physically.

**Comment by MasterEnderman** [comment]
If you reached the point where you're able to craft the Creative ME Storage Cell there is no reason to gate it behind another crafting recipe. At this stage you basically finished the modpack.
