### ISSUE TITLE
Steel Disappears

### ISSUE THREAD

**Issue by DeLittleCat** [al132mc/antimatter-chemistry#340]
I had just gotten my 48 Steel Ingots and put them in my RS storage system, as you do, and went to the nether to get Netherack for the Demon Ingot set up. I look back in the storage system... gone...

**Comment by OniyaMCD** [comment]
Could you show an image of your questbook for Chapter 3?  The recipe for the scarab (and hence the need for demon ingots) is revealed at a specific point in the quest tree.

**Comment by DeLittleCat** [comment]
Here you go: 
![Prog](https://user-images.githubusercontent.com/113717648/190886440-0a0442e7-8d8a-4199-a085-7a741844565f.png)

**Comment by DeLittleCat** [comment]
Tried to do it again in a creative world and it didn't work. Guess it was a one of.

**Comment by OniyaMCD** [comment]
From your screenshot, it shows that you claimed the reward for the 48 Steel quest.  If you read the questbook, it says that the steel will be consumed.
