### ISSUE TITLE
Add note to storage system quest to pick AE2 over RS

### ISSUE THREAD

**Issue by Ralsch** [al132mc/antimatter-chemistry#343]
I think RS has been included during rework recently.
But all rewards and the Loot Crates only contain AE2 items.

I suggest to also include RS items there.

**Comment by OniyaMCD** [comment]
Refined Storage for 1.12.2 has issues that impact tick speed, can cause server crashes, and even delete entire storage drives beyond recovery.  For that reason, the loot crates were rebalanced in the latest release to encourage use of AE2.

**Comment by Ralsch** [comment]
In that case I change my suggestion into "Remove RS from the ModPack entirely". ^^

**Comment by MasterEnderman** [comment]
We can't because many players build an rs system anyway and that way we would delete all of their items.

**Comment by Ralsch** [comment]
I see.
Maybe add a warning somewhere about this issue?
The related Quest emphasizes that there is no problem taking AE2 or RS. Maybe here would be a good place for a hint.

**Comment by MasterEnderman** [comment]
That's something we can definitely do!
