### ISSUE TITLE
content tweaker missing items removes recipies

### ISSUE THREAD

**Issue by adstheorganic** [al132mc/antimatter-chemistry#344]
Hi,

To begin I'm on the latest version and was before this issue, so that is not what has broken it,

So what happened was that I loaded up my world yesterday and it worked fine. I then loaded it up today and it gave an error when loading the world:

Forge Mod Loader detected missing registry entries.

There are 5 missing entries in this save
If you continue the missing entries will get removed.
Missing minecraft:items:
contenttweaker:patreon
contenttweaker:akliz
contenttweaker:discord
contenttweaker:youtube
contenttweaker:twitter

After loading into the world I noticed cellulose that had before now had the purple black checkered box texture of a missing item, and quite a few recipes not existing ( clay balls from block) and clay and dirt crafted with overworldian matter, to name a few.

I tried to load multiple older working backups, but they all show the same issue. 

--Thanks

**Comment by Timbroglio** [comment]
Hello! We're working on this issue now. It seems to be effecting everyone universally, and we're not sure what the cause is quite yet, but we'll keep you informed.

**Comment by Timbroglio** [comment]
Looks like the issue is with the curseforge launcher:
1. Click on the Minecraft Tab on the Left side of the CurseForge App.
2. Click "Three dots"/menu button next to the Create Custom Profile option.
3. Click Repair Installation option.

**Comment by adstheorganic** [comment]
Thanks, that worked, annoyingly though only once, it broke again after closing and relaunching curseforge and then reloading the instance which updated the launcher back into that broken version, so I guess, for now, you just have to do it every time before you launch of the game. Oh well will just have to deal with that for now and hopefully it gets fixed if it can be soon.
