### ISSUE TITLE
Unable to log into servers

### ISSUE THREAD

**Issue by Arthanax** [al132mc/antimatter-chemistry#345]
![Jre-legacy_Screenshot_2022 11 08_-_16 36 52 11](https://user-images.githubusercontent.com/51981752/200498648-777de774-df20-4a05-b528-0df45226729e.png)
This shows up whenever I try to log into my friends server. I tried reinstalling the modpack and playing on a fresh server but issue still occured. I think it may have something to do with apotheosis as is seems to introduce a new shears item and remove the minecraft one.

**Comment by MasterEnderman** [comment]
https://twitter.com/MojangStatus/status/1589822938995621888

**Comment by Arthanax** [comment]
Is that the root cause of the issue?

**Comment by Arthanax** [comment]
issue seems to have fixed itself, no idea what the cause was
