### ISSUE TITLE
I keep getting an error that prevents me from creating a singleplayer world

### ISSUE THREAD

**Issue by LittleTimmy52** [al132mc/antimatter-chemistry#347]
the log is here https://mclo.gs/D598M1a
i just got the pack, i tried to make a world, it gave me a crash screen and it happens every time

**Comment by OniyaMCD** [comment]
If you try to go into a single-player world after playing on a multi-player world, without restarting your launcher, it will crash.  This is a known RFTools bug, but the mod author still isn't sure why it happens.

Just close the launcher and start it up again.

**Comment by LittleTimmy52** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MasterEnderman** [comment]
#44
