### ISSUE TITLE
typo in the "Nice." (End) Quest

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#350]
it should be (69 69 69) not (69 169 69)

**Comment by RemagOfficial** [comment]
I don't think that's a typo, how would they accidentally type a 1 before 69 when 1 is across the keyboard from 6 and 9?

**Comment by MasterEnderman** [comment]
I know it's a typo, because I'm the one who made it in the first place. ^^ and don't question how I type, I'm weird. :D
