### ISSUE TITLE
Discord link invalid

### ISSUE THREAD

**Issue by Ralsch** [al132mc/antimatter-chemistry#351]
Not an issue with the pack, but about the invite link.

Every time I click it Discord tells me that the invite is invalid or has expired.
Do I miss something?

**Comment by MasterEnderman** [comment]
I just double checked and both places where I placed the invite link (main menu and quest book) booth use the official link posted in our discord.

https://discord.gg/4swu3fy

I have no idea why it gives you an errror.

**Comment by Ralsch** [comment]
I'm sorry. I wasn't specific enough. I didn't mean the links in the pack, but the one in the introduction on the github page. ^^

**Comment by MasterEnderman** [comment]
Well that's something that can easily be fixed. 😅 thank you for letting me know.

**Comment by Ralsch** [comment]
You're welcome. :-)
