### ISSUE TITLE
Freeze and Crash when Cutting Down Big Trees?

### ISSUE THREAD

**Issue by cyanidearsenic** [al132mc/antimatter-chemistry#357]
I'm having a weird issue where when I cut down a large tree, the game freezes and eventually has to be forced to close because it never comes back from not responding. 
The crash log is showing this error (although I'll attach the full log as well. Not sure if it'll help though since the game is not crashing on its own and has to be forced to quit.)
```
java.lang.NoSuchFieldError: field_184828_bq
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock
```
- This has happened after launching both online and offline. 
- I have the memory assigned to a max of 8GB.
- Oh, I also downloaded the pack via the FTB Launcher and then imported it into MultiMC because I don't like the FTB Launcher, but I would be surprised if that was the issue as I've done that with many packs without this issue.

Crash Log: [https://controlc.com/e105f5df](url)
I hope this site for the log is okay, Pastebin apparently thinks my crash log contains potentially offensive or questionable content which means I can't upload it without an account?

**Comment by MasterEnderman** [comment]
Yeah that's a known issue. For now just don't use any vanilla tools in combination with ore excavation. the responsible mod author is already aware of this issue.

**Comment by cyanidearsenic** [comment]
Okay, I'll do that.  Thanks for following up on the issue!
