### ISSUE TITLE
My quests are bugged

### ISSUE THREAD

**Issue by ThunderStorm0203** [al132mc/antimatter-chemistry#358]
I am currently in chapter 4 and trying to craft some Simulation Chambers, but it says "Unlocked in Chapter 4" when I move my cursor on it, and I can't see the recipe.

**Comment by MasterEnderman** [comment]
Have you finished all other quests? Some of them grant you a specific gamestage, which unlocks more recipes. if you have finished the quest that should give you access to a recipe, feel free to give you the corresponding gamestage via command.
`/gamestage add @p mummy`
