### ISSUE TITLE
Antimatter is no longer called antimatter

### ISSUE THREAD

**Issue by Telegy** [al132mc/antimatter-chemistry#373]
When you change language the white antimatter and light gray antimatter are no longer called antimatter, but just concrete

**Comment by FIRE-WATER799** [comment]
Yeah anyimatter is just renamed concrete. I mean you could translate them ìf you choose too

**Comment by MasterEnderman** [comment]
The reason for this is I only change the default localization. Once you choose a different localization the changed names no longer apply. Furthermore I'm not really motivated to translate the changes to all the languages minecraft offers.
