### ISSUE TITLE
crafted 4 evaporators for the quest book but only half of them counted...

### ISSUE THREAD

**Issue by 0bsidianFox** [al132mc/antimatter-chemistry#377]
made all 4 but it only shows 2/4 50%
![2023-09-10_21 54 05](https://github.com/SmashingMods/antimatter-chemistry/assets/72424605/ac648aa0-5bb0-4745-b2ba-e35ff1d5a760)

**Comment by 0bsidianFox** [comment]
Fixed it, Enabled cheat mode on HEI and gave myself the evaporators until it registered that I got them.

**Comment by MasterEnderman** [comment]
Note to myself: check if the quest is configured properly.
