### ISSUE TITLE
when i start a new minecraft world with antimatter chemistry modpack, it always automatically exit the world when loading in.

### ISSUE THREAD

**Issue by PuffYowl** [al132mc/antimatter-chemistry#378]
<img width="1280" alt="image" src="https://github.com/SmashingMods/antimatter-chemistry/assets/147394289/d8949111-285f-41ef-b487-32bc7b7d9fdf">

Do anyone know how to fix this issue when starting a minecraft world with Antimatter Chemistry modpack?

**Comment by PuffYowl** [comment]
pls fix this :(

**Comment by MasterEnderman** [comment]
How about providing an actual crash report or a log so that someone can actually figure out what's going on? A screenshot of a crash screen doesn't provide any useful information.

**Comment by RemagOfficial** [comment]
please post the log, the screenshot literally means nothing

**Comment by PuffYowl** [comment]
https://mclo.gs/QYZPgYs
here is the crash log, pls fix :(
