### ISSUE TITLE
Just so I don't forget it.

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#379]
https://www.curseforge.com/minecraft/mc-mods/ifpatcher

**Comment by Firecube247** [comment]
Not sure if this is relevant, however I would like to refer to #103

**Comment by Geolykt** [comment]
Just FYI the issues page is bridged to a discord channel so we will see when there is activity in stale issues. No need to explicitly bring up an issue that quickly. However, it might be best to create a new issue and referr to the old one if you bring up an issue that is closed for almost 4 years, but what's done is done.

**Comment by MasterEnderman** [comment]
The issue you mentioned won't be fixed when I get around to add this mod to antimatter chemistry as it's caused by a weird interaction with the "right click crops to harvest them" mod in this pack. I may need to replace it with another one and check if the plant interactor returns to it's normal behavior.
