### ISSUE TITLE
Server doesn't start. Error "JavaVersionOrPathError"

### ISSUE THREAD

**Issue by MikaMDF** [al132mc/antimatter-chemistry#381]
I have the newest Java versions installed and tried to run the ServerStart.bat on Windows 11. The file crashed and gave me this: 
ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java. com/en/download/manual. jsp

**** ERROR ****
There was an Error, Code: ""JavaVersionOrPathError""

**Comment by MasterEnderman** [comment]
Minecraft 1.12.2 requires Java 8 to run. Latest Java would probably be something like Java 21. install a useable version, otherwise the crash won't go away.
