### ISSUE TITLE
Crashing as I am creating new world in Antimatter Chemistry 1.45

### ISSUE THREAD

**Issue by Chaosreturns1** [al132mc/antimatter-chemistry#385]
https://mclo.gs/92QIDNL This is my crash log of the incident. 

I can load to the main menu. I tried to create a new world and I crashed with my included crash logs.

**Comment by rozbrajaczpoziomow** [comment]
If anyone was or wasn't curious as to what the solution for this issue was in this case:
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/58668179/cb37d748-d8ee-4c6f-a6aa-5033c2b6a4bd)
