### ISSUE TITLE
Another Server Issue for version 1.4.6 (Void Island Control)

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#386]
Besides it taking ages to get the serverfiles approved by curseforge, there already is another flaw to them. I try to replace mods with maintained forks whenever I can. I did the same with Void Island Control in the last update. But guess what, it's broken, if you actually try to run the server.

Reference: https://github.com/CaliforniaDemise/VoidIslandControl/issues/1

Feel free to delete the mod from your serverfiles as you probably wanna play on the flatworld anyway. The mod is currently only used in the skyblock / chunkchallenge map.

I you really wanna try the skyblock map replace the mod with the unmaintained original version "Void Island Control", but it's possible that the clients that want to connect to that server have to switch versions as well. I currently don't have the time to babysit curseforge for another 2 days, just to be sure that files will be approved this time.

Please have a little patience with me. We're already drafting up the LTS (long time support) version of the pack, which hopefully makes maintaining it easier for everyone involved. If you want to know more about it, check out the corresponding thread in the discord.

Have a great day. :)

**Comment by CaliforniaDemise** [comment]
Yeah fixed it. Thanks for posting the issue
