### ISSUE TITLE
Amount of energy displayed rounds up in a confusing way

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#39]
When doing the '10M FE' in chapter 3, the amount seems to round up (to the nearest 2,000FE as far as I can tell).

When the player has less than 2,000 FE remaining, task screens can say "10M FE OF 10M FE" submitted but also say 99% and the correct FE value in the quest book. This can be confusing if using low energy items to try to hit 10M FE with as little waste as possible.

When shown without holding shift in the quest book (display in background)
![2019-05-25_19 15 40](https://user-images.githubusercontent.com/51034324/58375510-8ba56a00-7f22-11e9-8474-d2204227ca2d.png)

When holding shift to see the finer amount
![2019-05-25_19 15 41](https://user-images.githubusercontent.com/51034324/58375517-c4ddda00-7f22-11e9-9aa6-22fdffd84f85.png)

**Comment by al132mc** [comment]
To be honest, I don't care. Thank you for your concern though.
