### ISSUE TITLE
singleplayer world lag

### ISSUE THREAD

**Issue by bullet23232** [al132mc/antimatter-chemistry#390]
my singleplayer newly made world is lagging while ram and memory is good

**Comment by MasterEnderman** [comment]
Please profile your world using spark (a mod in this pack) and share the link to it in this issue.
Here is a link to it's documentation: https://spark.lucko.me/docs/Command-Usage

**Comment by bullet23232** [comment]
idk how to use spark

**Comment by rozbrajaczpoziomow** [comment]
Enderman provided you with a link to spark's documentation, from there you'll be able to learn how to use Spark's commands.

**Comment by bullet23232** [comment]
i got this https://spark.lucko.me/RCRYMybLDd link from spark and also when i start modpack it, always popsup a valkyrien jvm with info that my java is outdatet but i have newest one

**Comment by MasterEnderman** [comment]
Thanks that's a good start, could you now please provide an in-game screenshot with the f3 menu open?

**Comment by bullet23232** [comment]
k but i can say that last time i had 0fps

**Comment by bullet23232** [comment]
![2024-04-18_20 13 13](https://github.com/SmashingMods/antimatter-chemistry/assets/111279897/1b02c59d-3115-44b6-a907-b158bf3f96c8)
here's screenshot with F3

**Comment by MasterEnderman** [comment]
Your Minecraft uses the integrated graphics card of your CPU no wonder you don't have any FPS.
Assuming your CPU is a i5-2540M I guess you're on a laptop. If you don't have a dedicated graphics card in your laptop you might need to remove some mods, that move some of the CPU load to the GPU as your integrated one isn't nearly powerful enough to handle rendering the game. Furthermore you only allocated roughly 3 GB of RAM so I assume you only have 4GB in total? If not try to allocate a bit more RAM.
Last note you're considering the warning from Valkyrie: you're using Java Version 1.8.0_51 the newest version would be 1.8.0_412 so you're roughly 350 versions behind. (but I don't think this makes much of a difference in comparison to the other issues mentioned before.

**Comment by bullet23232** [comment]
1 i heve only 4 Gb ram and 112 Gb memory
2 i'm on laptop with integrated graphic card
3 which mods delete to make more memory
4 Java was updated to version 1.8.0_411-b09

**Comment by MasterEnderman** [comment]
You could try disabling any combination of the following mods, but I don't guarantee that it will make the pack playable for you. I mean people have played the pack with roughly 2GB RAM allocated, but missing a dedicated graphics card is a completely different challenge and bottleneck.
- Nothrium
- Alfheim Lightning Engine
- Valkyrie
- Vintagefix
- maybe even CensoredASM (but this will probably break more things then it fixes)

I also won't spend any time trying to make the run on only a integrated GPU I'm sorry. So either you have to figure something out or look for another modpack.
