### ISSUE TITLE
Free the end & draconic evo crafters resetting upon completion & not working respectively 

### ISSUE THREAD

**Issue by bloodfang6921** [al132mc/antimatter-chemistry#391]
I need help on both fronts cause idk if its intentional or not cause the "free the end" quest resets upon completion of it and the fusion crafters & core are not working the crafters wont accept power and the core doesnt have a start button even when im using the correct recipe

**Comment by MasterEnderman** [comment]
The free the end quest is supposed to reset as it's repeatable, it should still unlock further progress once completed at least one time.

I probably need a screenshot of your fusion crafting setup to help you with that.

**Comment by bloodfang6921** [comment]
Ok well I figured it out i was just nor suplying enough power to the injectors so the system wasnt letting me complete the craft even when I had the correct recipe but thanks for the help on the free the end quest <3
