### ISSUE TITLE
The problem with "Interacting with plants"

### ISSUE THREAD

**Issue by EvgEnozZzZ** [al132mc/antimatter-chemistry#394]
In the new build version 1.4.8, the interfacer with plants does not work. I downloaded version 1.4.2, everything works fine there, but I'm already used to the new JEI and interface. how can I fix the problem with interacting with plants?

**Comment by rozbrajaczpoziomow** [comment]
The right-click to harvest mod has been replaced because of it duping with the Plant Interactor, you can put it back in your version if you want that functionality.
