### ISSUE TITLE
Cannot make cobblestone generator tier 2

### ISSUE THREAD

**Issue by EmmineValtine** [al132mc/antimatter-chemistry#397]
I have copied the recipe 100% accurately, and yet the generator will not be crafted. I can't progress without making this and nothing is working. Tried to give myself one through cheats and either I kept typing it wrong every time, or the game isn't recognizing that this item exists. Would love some help.

**Comment by HellWatcher** [comment]
Some screenshots will help with context.

**Comment by HellWatcher** [comment]
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/4584423/05fe5bec-a66a-40c7-9d29-27e3ba05fb92)
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/4584423/1f376bf9-aa9a-4630-93c6-7b992fb41a61)
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/4584423/40716f7e-b93e-4810-8b3d-7e56f9c7eeb6)

**Comment by EmmineValtine** [comment]
Tysm!!!! You are a godsend 🙏

**Comment by rozbrajaczpoziomow** [comment]
@HellWatcher In your case with screenshots you have the combiner paused (so you need to click on Resume for it to craft)

I tested on the most recent version and it works normally, if you wanna skip it though, you can either `/give @p tp:iron_cobblegen_block` or `/ftbquests editing_mode` (and edit the quest to a different item/instacomplete the quest)

**Comment by HellWatcher** [comment]
I was sending a step by step for EmmineValtine
