### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Chalky123b** [al132mc/antimatter-chemistry#4]
Had a crash report, (in Antimatter 0.4.12.zip (beta))
Hopefully it's a 1 off crash.
[crash-2019-04-20_19.51.05-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3100498/crash-2019-04-20_19.51.05-client.txt)

**Comment by al132mc** [comment]
Another user has reported this crash a few times as well.

**Comment by al132mc** [comment]
This is hopefully fixed in 0.4.14, but i'll leave this issue open until we're sure

**Comment by al132mc** [comment]
I have not had any reports of this bug in the last week or so, so I will assume it is fixed. If anyone else has this bug still feel free to create a new issue
