### ISSUE TITLE
Tweak Draconium Recipe

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#40]
Maybe consider crafting a draconium ingot with 4 dimenstional shards instead of 8. With the current recipe you already need 3 stack dimensional shards to craft the RFTools Quarry Card and don't get me starting on calculating the amount of dimensional shards you need for the direcrafting table.

**Comment by al132mc** [comment]
That's reasonable, I have changed it to 4 shards per ingot in 1.2.0
