### ISSUE TITLE
The loot table for rare loot crate has duplicate helium lights

### ISSUE THREAD

**Issue by iluha168** [al132mc/antimatter-chemistry#400]
Found a bug in version 1.4.8
The loot table for rare loot crate has duplicate helium lights. The alchemistry mod has 5 types of lights, i assume instead of duplicate helium there should be neon light.
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/44905605/6766915e-de10-4680-8271-7c838e0685ed)

Also, the achievement bright lights requires 6 types of chemicals, 5 of which are used to make lights, the exception being radon. (Radon is not used for neon lights irl either.) However, they are all noble gases, thus have a relation, so i'm not sure whether this is intentional or not.
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/44905605/f90291d2-75ef-4ded-bbc3-11e8e25f609f)

**Comment by ColorfulMarker** [comment]
can confirm the loot table part
