### ISSUE TITLE
cant progress

### ISSUE THREAD

**Issue by jack2058** [al132mc/antimatter-chemistry#401]
the rf question cant be interacted with I cant add rf the water quest worked thankfully but the rf just wont I try and click on it but nothing happens I hold a battery with more than ten million rf nothing happens I cant even compleate the quest in creative so I am just stuck please help.

**Comment by rozbrajaczpoziomow** [comment]
Use a task screen, select the RF quest and provide energy from the back.

**Comment by HellWatcher** [comment]
Use the screens awarded in this quest
![image](https://github.com/SmashingMods/antimatter-chemistry/assets/4584423/7b9eff56-d3f4-414a-8b83-558b853b8fb8)
