### ISSUE TITLE
Maybe reconsider adding LoliASM?

### ISSUE THREAD

**Issue by balt-dev** [al132mc/antimatter-chemistry#404]
Okay, hear me out. I know it's really good at what it does - assembly-level optimizations - and I know from slight experience that that is no small feat at all. It's a very impressive mod.

I don't feel comfortable playing a modpack with an optimization mod themed around _lolis_. Drag on me if you want, but it feels wrong.

**Comment by MasterEnderman** [comment]
Feel free to remove it from your instance.

**Comment by balt-dev** [comment]
Fair enough!
