### ISSUE TITLE
Liquifier not required for Water Bucket

### ISSUE THREAD

**Issue by codewarrior0** [al132mc/antimatter-chemistry#49]
Pack version 1.2.2

Water buckets can be created in the Chemical Combiner using moles of Water plus an empty Bucket, but the quest line insists I craft a Liquifier before continuing.

**Comment by al132mc** [comment]
Ah right, I must have added the water bucket recipe after I originally created that quest. Thanks for letting me know.

**Comment by al132mc** [comment]
The liquifier quest has been removed in v1.2.3
