### ISSUE TITLE
Alchemistry Ores

### ISSUE THREAD

**Issue by BaalSalmon** [al132mc/antimatter-chemistry#53]
Just a thought, but for tungsten: iron ore could be dissolved for a chance to get tungsten and manganese, due to wolframite (main ore of tungsten) containing iron. Perhaps wolframite could be taken as iron ore, so the iron ore has a theoretical chance to be wolframite, if you get what I mean...

To simplify, dissolving iron ore has a chance to give tungsten, something like 1 or 2 per ore

You'll have to do something similar to other ores :P

**Comment by al132mc** [comment]
Small amounts of byproducts have been added to iron, coal, and gold ores in Alchemistry v1.0.20. I will close this issue when the update is included in the pack.

**Comment by al132mc** [comment]
This was added a version or two ago, closing
