### ISSUE TITLE
Add the Sound Reloader mod

### ISSUE THREAD

**Issue by YaourtGG** [al132mc/antimatter-chemistry#6]
The mod's title is pretty self-explanatory, it creates a binding allowing you to reload Minecraft's sound manager without using F3 + T (which takes some time).
Sometimes, I have this issue and installed this mod locally so that I could solve it easily.

Link here : https://minecraft.curseforge.com/projects/sound-reloader

**Comment by wireman642** [comment]
Confirmed working when added to 1.0.0 and 1.0.2 versions of the pack when bound to MOUSE5 (an additional mouse button). Default reload is bound to P but that's a conflict. Recommend binding to HOME or NUMPAD8 as both don't conflict with anything.

**Comment by al132mc** [comment]
Added in 1.0.3
