### ISSUE TITLE
Quest Title / Quest Task mismatch

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#64]
Cobblestone Quest in Chapter 1

says "create 16 cobble" 
recquires "64 cobble" to complete

https://media.discordapp.net/attachments/586153421652885565/586153548325191680/2019-06-06_07.21.58.png?width=854&height=481

**Comment by al132mc** [comment]
Fixed in v1.2.6, thank you

**Comment by BaalSalmon** [comment]
### In Chapter 4
Pristine Blaze: Says collect 8, Requires 4
Pristine Zombie: Says collect 8, Requires 1

Didn't read thoroughly before copy+pasting

**Comment by BaalSalmon** [comment]
### In Chapter 6

Wyvern Fusion Crafting: Says collect 8, Requires 7
