### ISSUE TITLE
No way for Extra Utilities 2 Snow Globe to activate.

### ISSUE THREAD

**Issue by nman130** [al132mc/antimatter-chemistry#68]
Because the world is one large plains biome, the snow globe can't visit the requisite 7 biomes. This is necessary for the quantum quarry, which is unavailable due to this.

**Comment by al132mc** [comment]
It is possible with RFTools Dimensions, but I might consider changing the recipe for the quarry in any case

**Comment by MasterEnderman** [comment]
I would say leave the recipes as it is, that way the player have to use RFTools dimensions aswell and not just for collecting the dimensional shards. That way the player can unlocks the quantum quarry just a bit earlier then the quarry card from RFTools (which requires Draconium Stuff).

**Comment by al132mc** [comment]
Indeed, i'll just leave it as is.
