### ISSUE TITLE
Dimensional Shard ore generates in the nether

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#69]
![image](https://user-images.githubusercontent.com/24524662/59120664-4cc9d800-8956-11e9-8e3b-c836fc99ae69.png)
Playing on the official server.
This breaks the RFTools Dimensions progression, as you can farm the shards, without building a custom dimension

**Comment by al132mc** [comment]
Should be fixed in v1.2.6 (at least in new chunks...)
