### ISSUE TITLE
Mods to consider

### ISSUE THREAD

**Issue by pip69** [al132mc/antimatter-chemistry#7]
https://minecraft.curseforge.com/projects/refined-storage-addons

https://minecraft.curseforge.com/projects/akashic-tome

https://minecraft.curseforge.com/projects/tropicraft
  -  in theory would look good as an end goal.  Never used it though.

https://minecraft.curseforge.com/projects/the-midnight
  - Says its still in Alpha, but something to keep in mind

**Comment by YaourtGG** [comment]
I second Refined Storage Addons

**Comment by al132mc** [comment]
Added Refined Storage Addons in in v0.4.16, still unsure about the rest so i'll leave this open for now

**Comment by al132mc** [comment]
I have no plans to add any of these mods, but if anyone would like to make a case for them they can create a new issue and do so there.
