### ISSUE TITLE
[Suggestion] Add Shulker Pearl (Dark Utilities) to Shulker Module Loot

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#74]
![image](https://user-images.githubusercontent.com/24524662/59143348-92c08380-89ca-11e9-8925-46aaf19caba4.png)

![image](https://user-images.githubusercontent.com/24524662/59143363-a4a22680-89ca-11e9-98b4-e988559ad9e4.png)

That way the player don't have to spawn shulkers in the world just to get some pearls.

**Comment by al132mc** [comment]
Added in 1.2.7
