### ISSUE TITLE
[Suggestion] Add Dragon Scale (Tiny Progressions / Forbidden & Arcanus) to Dragon Module Loot

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#75]
![image](https://user-images.githubusercontent.com/24524662/59144907-dc19ce80-89dc-11e9-8ba0-feda278c2fff.png)

The only recipes for Dragonscales from F&A comes from the Dragon head which is unobtainable, due to the missing end cities.
![image](https://user-images.githubusercontent.com/24524662/59144918-07042280-89dd-11e9-8341-0115bbb2309c.png)

Dragin Scales (TP) only drop when killing the Dragon, so it would make sense to add them as possible loot next to dragon eggs, dragon breath and the DE stuff.
![image](https://user-images.githubusercontent.com/24524662/59144942-46cb0a00-89dd-11e9-9512-bdf955bd6478.png)

**Comment by al132mc** [comment]
I added the forbidden & arcanus ones in 1.2.7. I didn't realize until I was about to close this issue that tiny progressions had some as well. Will add next version

**Comment by MasterEnderman** [comment]
could you also add the dragon head as possible loot option. End Cities don't generate. So there isn't a way to obtain it either.

**Comment by al132mc** [comment]
TP scales and dragon head added in v1.2.8, thank you
