### ISSUE TITLE
[Suggestion] Add Rib of the Wither (Tiny Progressions) to Wither Module Loot

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#76]
![image](https://user-images.githubusercontent.com/24524662/59144959-8134a700-89dd-11e9-98f8-e2f83e1bdd0c.png)

That way the player can farm the Rib without needing to spawn the wither after making the module for it.

![image](https://user-images.githubusercontent.com/24524662/59144966-a2959300-89dd-11e9-9f72-95d32f080fc0.png)

**Comment by al132mc** [comment]
Added in 1.2.7
