### ISSUE TITLE
[Suggestion] Add Random Patches (Mod)

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/antimatter-chemistry#78]
https://minecraft.curseforge.com/projects/randompatches

The read and login timeouts are hardcoded in vanilla Minecraft, and are often not long enough for slower computers.
On Minecraft 1.9 and higher, RandomPatches allows you to configure the login timeout, and on Minecraft 1.12 and higher, the read timeout is also configurable.
By default, RandomPatches sets the read timeout to 90 seconds and the login timeout to 900 seconds.
The read timeout is the time the server waits for a response to the KeepAlive packet it sends every set interval. This interval can also be configured on Minecraft 1.9 and higher.
The read timeout is automatically rounded up to a product of the KeepAlive packet interval.
The login timeout generally has more impact than the read timeout.
This also sets the "fml.readTimeout" and "fml.loginTimeout" system properties.
These timeouts can be configured and take effect in-game, unless the NetHandlerPlayServer patches are disabled in the configuration.

**Comment by al132mc** [comment]
Added in 1.2.7
