### ISSUE TITLE
Info Calculator crashes game when pressing on some tabs

### ISSUE THREAD

**Issue by Vhisarion** [al132mc/antimatter-chemistry#79]
[info_calc_crash.txt](https://github.com/al132mc/antimatter-chemistry/files/3269703/info_calc_crash.txt)

Pressing one of the tabs you see at the right of the screenshot instantly crashes the game. 

[![Screenshot from Gyazo](https://gyazo.com/2f7ab461995044c5754780927c2ab5ad/raw)](https://gyazo.com/2f7ab461995044c5754780927c2ab5ad)

**Comment by al132mc** [comment]
oops wrong repo. https://github.com/al132mc/Volcano-Block/issues

**Comment by al132mc** [comment]
I created a new issue in the correct issue tracker
