### ISSUE TITLE
Items to add to the Dissolver

### ISSUE THREAD

**Issue by pip69** [al132mc/antimatter-chemistry#8]
From Atum
Alabaster & Porphyry: no specific suggestions, it should just be more useful than the normal stone types.
Marl: 100% kaolinite(3)   [its clay from atum]
All the  ring(x2), broach(x2), necklace (x3), scepter (x4), idols (x5)
The (x#) above is the number of rolls in the dissolver
below is the chemical from the dissolver and how many from a roll
 - silver: 80% silver(8)
 - gold: 80% gold(8)
 - sapphire: 80% potassium permanganate(4), 40% silver(8), 40% gold(8), 40% platinum(8)
 - ruby:  80% Iron Oxide (5), 80% strontium Carbonate (5), , 40% silver(8), 40% gold(8), 40% platinum(8)
 - emerald: 100% beryl(4), 100% chromium (4), 100% vanadium (2), , 40% silver(8), 40% gold(8), 40% platinum(8)
 - diamond: 40% gold(8), 40% silver(8), 40% carbon(16), 40% platinum(8)

**Comment by al132mc** [comment]
Added in v0.4.15, just uploaded. Thank you for the recipe suggestions.
