### ISSUE TITLE
Timedout

### ISSUE THREAD

**Issue by Waysepp** [al132mc/antimatter-chemistry#82]
Version 1.2.7

Problem:
When my friend connect to server he gets timed out.

Server Log
https://zerobin.net/?f49144389025842e#kYccYoPK0VrYyACd6oMmwoUn9iELXOerMhyMvwgVShE=

**Comment by Waysepp** [comment]
Tomorrow we try to change -Dfml.readTimeout=90 to 180 then try

**Comment by al132mc** [comment]
Default value has been increased in v1.2.8, though tthis is probably trouble on your end
