### ISSUE TITLE
Bonsai mod for tree automate

### ISSUE THREAD

**Issue by Krixiz** [al132mc/antimatter-chemistry#84]
This is a mod suggestion “Bonsai Tree” It will help player automate wood in early game and power generation

**Comment by finolawren** [comment]
I second this suggestion

**Comment by al132mc** [comment]
Unsure if i'll add it or not, but i'll leave this issue open

**Comment by MasterEnderman** [comment]
It isn't really needed. In the early game just shift around your trees and excavate them after they grown. Later you can build a very easy tree farm with industrial foregoing.

**Comment by RYBPLAYER** [comment]
I agree with MasterEnderman. Bonsai pots are unecessary.
