### ISSUE TITLE
When using a Redstone Furnace, Oak Wood converts into Dark Matter

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#85]
Running a Redstone Furnace with 2 speed augments. When putting Oak Wood (labeled from minecraft and ID #0017/0) from a RFdimension of wood, the output is Dark Matter.

In chat, you mentioned this might be solved by removing that wood type from the oreDictionary.

Screenshot below

![2019-06-12_13 02 09](https://user-images.githubusercontent.com/51034324/59372435-819eac00-8d15-11e9-938c-42aeec3497e0.png)

**Comment by al132mc** [comment]
Fixed in v1.2.8, thank you
