### ISSUE TITLE
Pristine Matter Quest Mismatch

### ISSUE THREAD

**Issue by IllusionaryApothecary** [al132mc/antimatter-chemistry#86]
Pristine Blaze Matter and Pristine Zombie Matter quests have mismatches between description & title/content.

Pristine Blaze Matter: Description says "Collect 8", finishes upon collecting 4.
Pristine Zombie Matter: Description says "Collect 8", finishes upon collecting 1.

**Comment by al132mc** [comment]
Fixed in v1.2.8, thank you
