### ISSUE TITLE
Uranium, in liquifier, converts to last liquid in liquifier tank

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#89]
Was pooring iron our of the liquifier with a TE pipe and a iron servo. had a hopper feeding in uranium for after. When uranium hit the liquifier, it continued to process like it was iron and increased the level as if i had added iron.

Screenshot
![2019-06-15_08 01 24](https://user-images.githubusercontent.com/51034324/59551247-8bf2bd00-8f44-11e9-8fa1-34c37813766f.png)

**Comment by al132mc** [comment]
Should be fixed in 1.2.9
