### ISSUE TITLE
Suggestion - Add Chisel

### ISSUE THREAD

**Issue by BaalSalmon** [al132mc/antimatter-chemistry#90]
Chisel would be a nice addition because it would add more variability to building, give more reason to decorate/care about looks, and it would add a more... homely feel to the antimatter world.

**Comment by MasterEnderman** [comment]
We already had this discussion before and decided to use lesser known decoration mods instead of just using chisel like most of the Modpacks today do.

**Comment by BaalSalmon** [comment]
Ah ok, that sounds nice

I'll close this then
