### ISSUE TITLE
can't craft a diamond pickaxe with the tetra crafting table

### ISSUE THREAD

**Issue by thealpabet** [al132mc/antimatter-chemistry#94]
I am unable to upgrade a stone pickaxe to a diamond one using the tetra crafting table. i saw it done in chosen architect's lava island episode 2. i am unable to do it.

**Comment by MasterEnderman** [comment]
Wrong repository this one is for the antimatter chemistry Modpack.

**Comment by thealpabet** [comment]
ah ok thanks sorry i don't really use github. can you post me a link to where i should post it?
