### ISSUE TITLE
Possibly wrong quest in chapter 4

### ISSUE THREAD

**Issue by findaldudu** [al132mc/antimatter-chemistry#98]
Is the "64x Cyan Antimatter" quest in Chapter 4 supposed to be a "64x Brown Antimatter" quest? 
Reasons:
1. There's already a cyan quest in Chapter 3.
2. You can only get brown antimatter after visiting Atum.
3. Neodymium, a product of brown antimatter, is needed to craft ender pearl.
Version: 1.2.9

**Comment by al132mc** [comment]
Fixed in 1.2.10, thank you
